// Run inside the isolated Linux build container after the owner reserves a version.
const fs = require('node:fs')
const path = require('node:path')
const { spawnSync } = require('node:child_process')
const { buildIdentity } = require('../qa/common.cjs')
const { collectNotices } = require('../mac/dependency-notices.cjs')
const { sha256, bundleInventory } = require('../mac/package-utils.cjs')
const project = path.resolve(__dirname, '../..')
if (process.argv.includes('--help')) { console.log('Usage on Linux x64: node scripts/linux/package.cjs ROOT_RESERVED_IDENTITY_JSON NEW_OUTPUT_DIRECTORY\nThe Docker coordinator normally invokes this entrypoint. No version reservation or publishing occurs.'); process.exit(0) }
const [identityFile, output] = process.argv.slice(2)
if (!identityFile || !output || process.platform !== 'linux' || process.arch !== 'x64') throw new Error('Usage on Linux x64: node scripts/linux/package.cjs BUILD_IDENTITY_JSON NEW_OUTPUT_DIRECTORY')
const manifest = JSON.parse(fs.readFileSync(identityFile, 'utf8'))
if (!/^\d+\.\d+\.\d+$/.test(manifest.version) || !manifest.buildId || !manifest.source?.commit || !manifest.source?.workingTreeSha256) throw new Error('A root-reserved version and complete frozen source identity are required')
fs.mkdirSync(output, { mode: 0o700 })
const result = { status: 'building', platform: process.platform, arch: process.arch, version: manifest.version, buildId: manifest.buildId, checks: [] }
const json = (name, value) => fs.writeFileSync(path.join(output, name), JSON.stringify(value, null, 2) + '\n')
const save = () => json('result.json', result)
function command(name, executable, args, env = process.env) {
  const fd = fs.openSync(path.join(output, name + '.log'), 'wx')
  const run = spawnSync(executable, args, { cwd: project, env, stdio: ['ignore', fd, fd], timeout: 900000 })
  fs.closeSync(fd)
  result.checks.push({ name, command: [executable, ...args], exitCode: run.status, signal: run.signal, error: run.error?.message })
  save()
  if (run.status !== 0) throw new Error(name + ' failed; see retained log')
}
try {
  save()
  command('help-consistency', process.execPath, ['scripts/help/generate.cjs', '--check'])
  command('locale-consistency', process.execPath, ['scripts/locales/check.cjs'])
  command('typescript', process.execPath, ['node_modules/typescript/bin/tsc'])
  command('compile', process.execPath, ['node_modules/vite/bin/vite.js', 'build'])
  manifest.compiled = buildIdentity()
  manifest.platform = 'linux'; manifest.arch = 'x64'; manifest.signing = 'unsigned'
  manifest.runtime = { node: process.version, osRelease: fs.readFileSync('/etc/os-release', 'utf8') }
  json('build-identity.json', manifest)
  const notices = collectNotices(project)
  json('dependency-inventory.json', notices.inventory)
  fs.writeFileSync(path.join(output, 'THIRD_PARTY_NOTICES.txt'), notices.text)
  const extraResources = ['scripts/ziaf.cjs', 'scripts/ziaforge-mcp.cjs', 'docs/AGENT_CONTROL.md', 'docs/USER_GUIDE.md', 'LICENSE'].map(file => ({ from: path.join(project, file), to: path.basename(file) }))
  for (const file of ['build-identity.json', 'dependency-inventory.json', 'THIRD_PARTY_NOTICES.txt']) extraResources.push({ from: path.join(output, file), to: file })
  extraResources.push({ from: path.join(project, 'node_modules/electron/dist/LICENSE'), to: 'ELECTRON_LICENSE.txt' }, { from: path.join(project, 'node_modules/electron/dist/LICENSES.chromium.html'), to: 'LICENSES.chromium.html' })
  const config = { extends: path.join(project, 'electron-builder.json5'), directories: { output: path.join(output, 'artifacts') }, extraMetadata: { version: manifest.version, homepage: 'https://github.com/ZIAForge/ZIAForge' }, buildVersion: manifest.version, asarUnpack: ['node_modules/node-pty/**/*'], extraResources,
    linux: { target: [{ target: 'deb', arch: ['x64'] }], artifactName: `ZIAForge-${manifest.buildId}-linux-amd64.deb` } }
  json('builder-config.json', config)
  command('package', process.execPath, ['node_modules/electron-builder/cli.js', '--linux', 'deb', '--x64', '--publish', 'never', '--config', path.join(output, 'builder-config.json')], { ...process.env, CI: 'true' })
  const artifacts = path.join(output, 'artifacts')
  const debs = fs.readdirSync(artifacts).filter(file => file.endsWith('.deb'))
  if (debs.length !== 1) throw new Error('Expected exactly one fresh .deb')
  const deb = path.join(artifacts, debs[0])
  command('deb-info', '/usr/bin/dpkg-deb', ['--info', deb])
  command('deb-files', '/usr/bin/dpkg-deb', ['--contents', deb])
  const fields = spawnSync('/usr/bin/dpkg-deb', ['--field', deb, 'Package', 'Version', 'Architecture'], { encoding: 'utf8' })
  if (fields.status !== 0 || !fields.stdout.includes('Version: ' + manifest.version) || !fields.stdout.includes('Architecture: amd64')) throw new Error('Wrong .deb identity')
  const app = path.join(artifacts, 'linux-unpacked')
  const asar = require('@electron/asar')
  const embedded = JSON.parse(asar.extractFile(path.join(app, 'resources/app.asar'), 'package.json').toString())
  if (embedded.version !== manifest.version) throw new Error('ASAR package version mismatch')
  command('native-pty', path.join(app, 'ziaforge'), [path.join(project, 'scripts/linux/native-smoke.cjs'), app, path.join(output, 'native-pty.json')], { ...process.env, ELECTRON_RUN_AS_NODE: '1' })
  const native = JSON.parse(fs.readFileSync(path.join(output, 'native-pty.json'), 'utf8'))
  if (native.status !== 'passed') throw new Error('Packaged Linux native PTY failed')
  const inventory = bundleInventory(app)
  json('app-inventory.json', inventory)
  fs.writeFileSync(path.join(output, 'SHA256SUMS'), `${sha256(deb)}  artifacts/${debs[0]}\n${sha256(path.join(app, 'resources/app.asar'))}  artifacts/linux-unpacked/resources/app.asar\n`)
  Object.assign(result, { status: 'passed', deb: path.relative(output, deb), app: path.relative(output, app), debSha256: sha256(deb), bundleInventorySha256: inventory.digest, compiled: manifest.compiled, gui: 'not yet verified; run the separate two-container installed-package smoke', signed: false })
} catch (error) { result.status = 'failed'; result.error = error.stack; process.exitCode = 1 }
result.finishedAt = new Date().toISOString(); save()
