import { uiText } from '../../uiText'
import { useEffect, useRef, useState } from 'react'
import { Bot, Camera, Square, ArrowUp, Settings2, Terminal, Globe, LoaderCircle } from 'lucide-react'
import type { AssistantState, ControlStatus } from '../../../shared/control'
import { useStore } from '../../store'
import { MarkdownMessage } from '../../components/MarkdownMessage'
export function ArchitectAssistant(){
  const {settings}=useStore(),ru=(settings?.uiLanguage??'en').startsWith('ru')
  const [state,setState]=useState<AssistantState>({entries:[],busy:false}),[control,setControl]=useState<ControlStatus>(),[text,setText]=useState(''),[instance,setInstance]=useState(''),[error,setError]=useState(''),[image,setImage]=useState(''),[manual,setManual]=useState(false),[command,setCommand]=useState('{"method":"system.summary"}'),[receipt,setReceipt]=useState('')
  const input=useRef<HTMLTextAreaElement>(null)
  useEffect(()=>{let alive=true;const refresh=()=>{void window.ziafAPI.control.assistantState().then(s=>{if(alive)setState(s)}).catch(e=>{if(alive)setError(e.message)})};refresh();void window.ziafAPI.control.status().then(s=>{if(alive)setControl(s)}).catch(e=>{if(alive)setError(e.message)});const timer=setInterval(refresh,1500);return()=>{alive=false;clearInterval(timer)}},[])
  const send=async()=>{if(state.busy||!text.trim())return;const message=text;setText('');setState(s=>({...s,busy:true}));setError('');input.current?.focus();try{setState(await window.ziafAPI.control.assistantSend({text:message,instanceId:instance||undefined}))}catch(e){setError(e instanceof Error?e.message:String(e));setState(s=>({...s,busy:false}))}}
  const execute=async()=>{try{const request=JSON.parse(command);const result=await(instance?window.ziafAPI.control.remote({instanceId:instance,request}):window.ziafAPI.control.execute(request));setReceipt(JSON.stringify(result,null,2))}catch(e){setError(e instanceof Error?e.message:String(e))}}
  return <div className="flex h-full min-h-0 flex-col"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-zinc-800 p-5"><h1 className="flex items-center gap-2 text-lg font-semibold"><Bot className="text-orange-500"/>{uiText("ZIAF · Application architect", undefined, (ru) ? 'ru' : undefined)}</h1><div className="flex items-center gap-3"><Globe size={16}/><select aria-label={uiText("Instance")} className="zf-control border border-zinc-700 bg-zinc-900 p-2 text-xs" value={instance} onChange={e=>setInstance(e.target.value)}><option value="">{uiText("This ZIAForge", undefined, (ru) ? 'ru' : undefined)}</option>{control?.instances.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select><button aria-label={uiText("Assistant settings", undefined, (ru) ? 'ru' : undefined)} onClick={()=>useStore.getState().setActiveTab('settings')}><Settings2 size={18}/></button><button aria-label={uiText("Screenshot")} onClick={()=>{void(instance?window.ziafAPI.control.remote({instanceId:instance,request:{method:'system.screenshot'}}):window.ziafAPI.control.execute({method:'system.screenshot'})).then(result=>setImage((result as {dataUrl:string}).dataUrl)).catch(e=>setError(e.message))}}><Camera size={18}/></button><button aria-label={uiText("Manual commands")} onClick={()=>setManual(v=>!v)}><Terminal size={18}/></button></div></header>
    <div className="flex-1 space-y-4 overflow-y-auto p-5"><p className="text-sm text-zinc-400">{uiText("The architect reads projects, chats and stages, clarifies requirements and controls the application within its granted permissions.", undefined, (ru) ? 'ru' : undefined)}</p>{state.entries.map(e=><article key={e.id} className={`zf-surface border p-4 ${e.role==='user'?'ml-12 border-orange-500/25 bg-orange-950/20':'border-zinc-800 bg-[#15171a]'}`}><p className="mb-2 text-xs text-zinc-500">{e.role==='user'?(uiText("You", undefined, (ru) ? 'ru' : undefined)):e.role==='command'?(uiText("Command receipt", undefined, (ru) ? 'ru' : undefined)):'ZIAForge'}</p>{e.role==='command'?<details><summary className="cursor-pointer text-xs">{uiText("Show receipt", undefined, (ru) ? 'ru' : undefined)}</summary><pre className="mt-3 max-h-80 overflow-auto whitespace-pre-wrap text-xs">{e.text}</pre></details>:<MarkdownMessage text={e.text}/>} {e.image&&<img src={e.image} alt={uiText("ZIAForge screenshot")} className="mt-3 max-w-full rounded-xl border border-zinc-700"/>}</article>)}{image&&<img src={image} alt={uiText("ZIAForge screenshot")} className="zf-surface max-w-full border border-zinc-700"/>}{manual&&<section className="zf-surface space-y-3 border border-zinc-700 p-4"><textarea aria-label={uiText("Application command JSON")} className="min-h-24 w-full bg-zinc-950 p-3 font-mono text-xs" value={command} onChange={e=>setCommand(e.target.value)}/><button className="zf-control bg-orange-600 px-3 py-2 text-xs" onClick={()=>void execute()}>{uiText("Run application command", undefined, (ru) ? 'ru' : undefined)}</button><pre className="max-h-80 overflow-auto whitespace-pre-wrap text-xs">{receipt}</pre></section>}</div>
    <footer className="border-t border-zinc-800 p-4">{(error||state.error)&&<p role="alert" className="mb-2 text-sm text-red-300">{error||state.error}</p>}<div className="zf-surface border border-zinc-700 bg-[#111215] p-3"><textarea ref={input} aria-label={uiText("Message architect", undefined, (ru) ? 'ru' : undefined)} className="min-h-20 w-full resize-none bg-transparent text-sm outline-none" value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void send()}}} placeholder={uiText("Discuss an idea or ask for project status…", undefined, (ru) ? 'ru' : undefined)}/><div className="flex items-center justify-between text-xs text-zinc-400"><span>{state.busy?<span className="flex gap-2"><LoaderCircle size={14} className="animate-spin"/>{uiText("Architect is working", undefined, (ru) ? 'ru' : undefined)}</span>:control?.assistantPreset|| (uiText("Helper preset", undefined, (ru) ? 'ru' : undefined))}</span>{state.busy?<button aria-label={uiText("Stop architect")} className="zf-control bg-orange-600 p-2 text-white" onClick={()=>void window.ziafAPI.control.assistantStop()}><Square size={16}/></button>:<button disabled={!text.trim()} aria-label={uiText("Send to architect")} className="zf-control bg-orange-600 p-2 text-white disabled:opacity-40" onClick={()=>void send()}><ArrowUp size={16}/></button>}</div></div></footer>
  </div>
}
