import { uiText } from '../../uiText'
import { useEffect, useState } from 'react'
import { Globe, KeyRound, Monitor, Bot, Plus, Trash2, Save, RefreshCw, ExternalLink } from 'lucide-react'
import type { ControlConfig, ControlStatus } from '../../../shared/control'
import { useStore } from '../../store'
export function ControlSettings(){
  const {settings,presets}=useStore(),ru=(settings?.uiLanguage??'en').startsWith('ru')
  const [status,setStatus]=useState<ControlStatus>(),[draft,setDraft]=useState<ControlConfig>(),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const remote=(window as Window & {ziafRemote?:boolean}).ziafRemote
  const refresh=()=>window.ziafAPI.control.status().then(s=>{setStatus(s);const {endpoint,accessToken,telegramConfigured,telegramStatus,running,error:failure,...config}=s;void endpoint;void accessToken;void telegramConfigured;void telegramStatus;void running;void failure;setDraft(config)})
  useEffect(()=>{void refresh().catch(e=>setError(e.message))},[])
  const action=async(fn:()=>Promise<ControlStatus>)=>{setBusy(true);setError('');try{const s=await fn();setStatus(s);await refresh()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
  const field=(v:Partial<ControlConfig>)=>setDraft(d=>d?{...d,...v}:d)
  if(!draft)return <p role="status">{error|| (uiText("Loading…", undefined, (ru) ? 'ru' : undefined))}</p>
  const input='zf-control w-full border border-zinc-700 bg-[#101114] px-3 py-2 text-sm'
  return <section className="space-y-5" data-testid="control-settings"><h2 className="flex items-center gap-2 text-lg font-semibold"><Globe size={20}/>{uiText("Remote control", undefined, (ru) ? 'ru' : undefined)}</h2>
    {remote&&<p className="text-sm text-zinc-400">{uiText("Connection permissions and secrets are managed in the local owner application.", undefined, (ru) ? 'ru' : undefined)}</p>}
    <fieldset disabled={busy||remote} className="space-y-4">
      <label className="flex items-center gap-2"><input type="checkbox" checked={draft.enabled} onChange={e=>field({enabled:e.target.checked})}/>{uiText("Enable browser interface and API", undefined, (ru) ? 'ru' : undefined)}</label>
      <div className="grid gap-3 md:grid-cols-3"><label>{uiText("Address", undefined, (ru) ? 'ru' : undefined)}<select className={input} value={draft.host} onChange={e=>field({host:e.target.value as ControlConfig['host']})}><option value="127.0.0.1">127.0.0.1 · {uiText("this computer", undefined, (ru) ? 'ru' : undefined)}</option><option value="0.0.0.0">0.0.0.0 · {uiText("network", undefined, (ru) ? 'ru' : undefined)}</option></select></label><label>{uiText("Port", undefined, (ru) ? 'ru' : undefined)}<input className={input} type="number" min="1024" max="65535" value={draft.port} onChange={e=>field({port:Number(e.target.value)})}/></label><label>{uiText("Connection access", undefined, (ru) ? 'ru' : undefined)}<select className={input} value={draft.scope} onChange={e=>field({scope:e.target.value as ControlConfig['scope']})}><option value="read">{uiText("Read only", undefined, (ru) ? 'ru' : undefined)}</option><option value="operate">{uiText("Operate application", undefined, (ru) ? 'ru' : undefined)}</option></select></label></div>
      <p className="text-xs text-zinc-400">{uiText("For Internet connections use an HTTPS proxy, VPN or SSH tunnel.", undefined, (ru) ? 'ru' : undefined)}</p>
      <div className="zf-surface border border-zinc-800 p-4"><p className="flex items-center gap-2"><KeyRound size={16}/>{uiText("Access token", undefined, (ru) ? 'ru' : undefined)}</p><input aria-label={uiText("Access token", undefined, (ru) ? 'ru' : undefined)} className={`${input} mt-2 font-mono text-xs`} type="password" readOnly value={status?.accessToken??''}/><div className="mt-2 flex gap-3"><button type="button" onClick={()=>{if(status?.accessToken)void navigator.clipboard.writeText(status.accessToken).catch(e=>setError(e.message))}}>{uiText("Copy", undefined, (ru) ? 'ru' : undefined)}</button><button type="button" onClick={()=>void action(()=>window.ziafAPI.control.rotateToken())}>{uiText("Rotate token and disconnect clients", undefined, (ru) ? 'ru' : undefined)}</button></div></div>
      <h3 className="flex items-center gap-2 font-medium"><Bot size={18}/>{uiText("Application architect", undefined, (ru) ? 'ru' : undefined)}</h3><label>{uiText("Assistant preset", undefined, (ru) ? 'ru' : undefined)}<select className={input} value={draft.assistantPreset} onChange={e=>field({assistantPreset:e.target.value})}><option value="">{uiText("Default helper preset", undefined, (ru) ? 'ru' : undefined)}</option>{presets.map(p=><option key={p.name}>{p.name}</option>)}</select></label><label className="flex gap-2"><input type="checkbox" checked={draft.assistantOperate} onChange={e=>field({assistantOperate:e.target.checked})}/>{uiText("Assistant may operate the application", undefined, (ru) ? 'ru' : undefined)}</label>
      <div className="zf-surface border border-orange-500/25 p-4"><label className="flex items-center gap-2"><Monitor size={16}/><input data-testid="native-computer-owner" type="checkbox" checked={draft.nativeComputer} onChange={e=>field({nativeComputer:e.target.checked})}/>{uiText("Native computer access", undefined, (ru) ? 'ru' : undefined)}</label><p className="mt-2 text-xs text-zinc-400">{uiText("Only the owner can grant this here. Without this grant the assistant uses application commands; choose Claude or API with native tools disabled.", undefined, (ru) ? 'ru' : undefined)}</p></div>
      <h3 className="font-medium">Telegram</h3><label className="flex gap-2"><input type="checkbox" checked={draft.telegramEnabled} onChange={e=>field({telegramEnabled:e.target.checked})}/>{uiText("Enable owner bot", undefined, (ru) ? 'ru' : undefined)}</label><div className="grid gap-3 md:grid-cols-2"><label>{uiText("Bot token")}<input className={input} type="password" autoComplete="off" value={draft.telegramToken??''} placeholder={status?.telegramConfigured?(uiText("Saved; blank preserves token", undefined, (ru) ? 'ru' : undefined)):''} onChange={e=>field({telegramToken:e.target.value||undefined})}/></label><label>{uiText("Numeric Telegram owner ID", undefined, (ru) ? 'ru' : undefined)}<input className={input} inputMode="numeric" value={draft.telegramOwner} onChange={e=>field({telegramOwner:e.target.value})}/></label></div>
      <h3 className="font-medium">{uiText("Other ZIAForge instances", undefined, (ru) ? 'ru' : undefined)}</h3>{draft.instances.map(i=><div key={i.id} className="zf-surface space-y-2 border border-zinc-800 p-3"><div className="grid gap-2 md:grid-cols-3">{(['name','url','token'] as const).map(k=><input key={k} aria-label={uiText({ name: 'Instance name', url: 'Instance URL', token: 'Instance access token' }[k])} type={k==='token'?'password':'text'} className={input} placeholder={uiText(k==='token'&&i.hasToken?'Saved token':{ name: 'Instance name', url: 'Instance URL', token: 'Instance access token' }[k])} value={i[k]??''} onChange={e=>field({instances:draft.instances.map(other=>other.id===i.id?{...other,[k]:e.target.value||undefined}:other)})}/>)}</div><div className="flex items-center gap-4"><button type="button" aria-label={uiText("Remove instance")} onClick={()=>field({instances:draft.instances.filter(o=>o.id!==i.id)})}><Trash2 size={15}/></button><button type="button" className="flex items-center gap-2" onClick={()=>{if(status?.endpoint)void window.ziafAPI.openExternal(`${status.endpoint}/?instance=${encodeURIComponent(i.id)}`);else setError(uiText("Save and enable the browser interface to switch instances.", undefined, (ru) ? 'ru' : undefined))}}><ExternalLink size={14}/>{uiText("Open instance interface", undefined, (ru) ? 'ru' : undefined)}</button></div></div>)}<button type="button" className="flex items-center gap-2" onClick={()=>field({instances:[...draft.instances,{id:crypto.randomUUID(),name:`ZIAForge ${draft.instances.length+1}`,url:'http://127.0.0.1:43210'}]})}><Plus size={16}/>{uiText("Add instance", undefined, (ru) ? 'ru' : undefined)}</button>
      <button className="zf-control flex items-center gap-2 bg-orange-600 px-4 py-2 text-white" type="button" onClick={()=>void action(()=>window.ziafAPI.control.configure(draft))}><Save size={16}/>{uiText("Save access settings", undefined, (ru) ? 'ru' : undefined)}</button>
    </fieldset>
    <p className="text-xs text-zinc-400">{status?.running?status.endpoint:(uiText("Server disabled", undefined, (ru) ? 'ru' : undefined))} · Telegram: {status?.telegramStatus}</p>{status?.endpoint&&<button type="button" className="flex gap-2" onClick={()=>void window.ziafAPI.openExternal(status.endpoint!)}><ExternalLink size={16}/>{uiText("Open interface", undefined, (ru) ? 'ru' : undefined)}</button>}<button type="button" className="flex gap-2 text-xs" onClick={()=>void refresh()}><RefreshCw size={14}/>{uiText("Refresh status", undefined, (ru) ? 'ru' : undefined)}</button>{(error||status?.error)&&<p role="alert" className="text-sm text-red-300">{error||status?.error}</p>}
  </section>
}
