import { statusLabel } from './localizedLabels'
import { uiText } from '../../uiText'
import { useEffect, useState } from 'react'
import { Download, RefreshCw, Save } from 'lucide-react'
import type { UpdateStatus, UpdateConfig } from '../../../shared/control'
import { useStore } from '../../store'
export function UpdatesPanel(){
  const ru=(useStore(s=>s.settings?.uiLanguage)??'en').startsWith('ru')
  const [status,setStatus]=useState<UpdateStatus>(),[config,setConfig]=useState<UpdateConfig>({repository:'',channel:'preview',automatic:false}),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  useEffect(()=>{const timer=setInterval(()=>{void window.ziafAPI.updates.status().then(setStatus).catch(()=>{})},1500);void window.ziafAPI.updates.status().then(s=>{setStatus(s);setConfig({repository:s.repository??'',channel:s.currentChannel,automatic:s.automatic??false})}).catch(e=>setError(e.message));return()=>clearInterval(timer)},[])
  const action=async(fn:()=>Promise<UpdateStatus>)=>{setBusy(true);setError('');try{setStatus(await fn())}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
  return <section className="space-y-4" data-testid="updates-settings"><h2 className="flex items-center gap-2 text-lg font-semibold"><Download size={20}/>{uiText("Updates", undefined, (ru) ? 'ru' : undefined)}</h2><label className="block">{uiText("GitHub owner/repository")}<input className="zf-control mt-2 w-full border border-zinc-700 bg-zinc-950 p-3 text-sm" value={config.repository} placeholder="owner/repository" onChange={e=>setConfig(c=>({...c,repository:e.target.value}))}/></label><label className="block">{uiText("Channel", undefined, (ru) ? 'ru' : undefined)}<select className="zf-control ml-3 border border-zinc-700 bg-zinc-950 p-2" value={config.channel} onChange={e=>setConfig(c=>({...c,channel:e.target.value as UpdateConfig['channel']}))}><option value="stable">{uiText("Stable")}</option><option value="preview">{uiText("Preview")}</option></select></label><label className="flex gap-2"><input type="checkbox" checked={config.automatic} onChange={e=>setConfig(c=>({...c,automatic:e.target.checked}))}/>{uiText("Automatically check and download", undefined, (ru) ? 'ru' : undefined)}</label><p className="text-xs text-zinc-400">{uiText("Stable receives stable releases only. Preview includes prereleases. macOS automatic installation requires a signed application and published update metadata.", undefined, (ru) ? 'ru' : undefined)}</p><div className="flex flex-wrap gap-3"><button disabled={busy} className="zf-control flex gap-2 border border-zinc-700 p-2" onClick={()=>void action(()=>window.ziafAPI.updates.configure(config))}><Save size={16}/>{uiText("Save", undefined, (ru) ? 'ru' : undefined)}</button><button disabled={busy} className="zf-control flex gap-2 border border-zinc-700 p-2" onClick={()=>void action(()=>window.ziafAPI.updates.check())}><RefreshCw size={16}/>{uiText("Check", undefined, (ru) ? 'ru' : undefined)}</button>{status?.state==='available'&&<button onClick={()=>void action(()=>window.ziafAPI.updates.download())}>{uiText("Download", undefined, (ru) ? 'ru' : undefined)}</button>}{status?.state==='downloaded'&&<button onClick={()=>void window.ziafAPI.updates.install().catch(e=>setError(e.message))}>{uiText("Install and restart", undefined, (ru) ? 'ru' : undefined)}</button>}</div><p role="status" className="text-sm text-zinc-400">{status ? statusLabel(status.state, ru) : ''} {status?.version} {status?.message}</p>{error&&<p role="alert" className="text-red-300">{error}</p>}</section>
}
