import fs from 'node:fs/promises'
import path from 'node:path'
import { createHash } from 'node:crypto'
import { test, expect } from './fixtures'
import { startClaudeConnectorFixture } from './fixtures/claude-connector-server'

// The normal isolated Electron harness blocks real providers and keeps credentials out of the profile.
test.use({ providerFixture: 'codex' })

test('Claude Messages loopback fixture retains explicit native decisions, attachments and immutable files after full Quit without replay', async ({ app }, testInfo) => {
  test.setTimeout(180_000)
  const server = await startClaudeConnectorFixture()
  const snapshot = () => app.window.evaluate(() => window.ziafAPI.agentSessions.attach({ taskId: 'task-e2e', chatId: 'chat-main' }))
  const openTask = () => app.window.getByRole('button', { name: 'E2E Workspace', exact: true }).click()
  const posts = () => server.records.filter(item => item.method === 'POST')
  const downloads = () => server.records.filter(item => item.path.startsWith('/v1/files/'))
  const localSentinel = testInfo.outputPath('profile', 'project', 'worktrees', 'task-e2e', server.serverFilename)
  const sourceVersion = (JSON.parse(await fs.readFile(new URL('../package.json', import.meta.url), 'utf8')) as { version: string }).version
  const currentBuild = async () => {
    const identity = await app.window.evaluate(() => window.ziafAPI.getAppVersion())
    expect(identity.version).toBe(sourceVersion)
    await expect(app.window.getByRole('button', { name: `Version ${identity.fullVersion}`, exact: true })).toBeVisible()
    return identity
  }
  try {
    const initialBuild = await currentBuild()
    await app.window.getByRole('button', { name: 'Connections', exact: true }).first().click()
    await app.window.getByTestId('api-connection-name').fill('Local Claude Messages fixture')
    await app.window.getByTestId('api-connection-url').fill(server.origin)
    await app.window.getByTestId('api-connection-model').fill('claude-fixture')
    await app.window.getByTestId('api-connection-transport').selectOption('anthropic-messages')
    await app.window.getByTestId('api-connection-profile').selectOption('claude-connector-v1')
    await expect(app.window.getByTestId('api-claude-mode')).toHaveValue('caller')
    await expect(app.window.getByTestId('api-claude-permissions')).toHaveValue('manual')
    await app.window.getByTestId('api-connection-save').click()
    await expect(app.window.getByTestId('api-connection-saved')).toBeVisible()
    const [connection] = await app.window.evaluate(() => window.ziafAPI.apiConnections.list())
    expect(connection).toMatchObject({ baseUrl: server.origin, transport: 'anthropic-messages', profile: 'claude-connector-v1', hasApiKey: false, claude: { mode: 'caller', permissionMode: 'manual', nativeTools: [] } })
    await app.window.getByTestId(`api-claude-inspect-${connection.id}`).click()
    const capabilities = app.window.getByTestId('api-claude-capabilities')
    await expect(capabilities).toBeVisible()
    await expect(capabilities).toContainText('Remaining capacity is unknown, not zero usage.')
    expect(server.generationCount()).toBe(0)
    await app.window.getByTestId(`api-connection-${connection.id}`).getByRole('button', { name: 'Edit', exact: true }).click()
    await app.window.getByTestId('api-claude-mode').selectOption('native')
    await app.window.getByTestId('api-claude-tool-Write').check()
    await app.window.getByTestId('api-claude-tool-AskUserQuestion').check()
    await app.window.getByTestId('api-claude-max-turns').fill('7')
    await app.window.getByTestId('api-claude-max-tokens').fill('2048')
    await app.window.getByTestId('api-connection-save').click()
    await expect(app.window.getByTestId('api-connection-saved')).toBeVisible()
    const [savedConnection] = await app.window.evaluate(() => window.ziafAPI.apiConnections.list())
    expect(savedConnection.claude).toMatchObject({ mode: 'native', permissionMode: 'manual', nativeTools: ['Write', 'AskUserQuestion'], maxTurns: 7, maxTokens: 2048, historyMode: 'reject' })
    await app.window.screenshot({ path: testInfo.outputPath('01-claude-saved-connection.png'), fullPage: true })

    await openTask()
    await app.window.getByTestId('composer-preset-button').click()
    await app.window.getByTestId('composer-custom-option').click()
    await app.window.getByTestId('composer-provider-button').click()
    await app.window.getByTestId('agent-chat-provider').selectOption('api')
    await app.window.getByTestId('agent-chat-api-connection').selectOption(connection.id)
    await app.window.getByTestId('agent-chat-apply').click()
    await app.window.getByTestId('composer-options-button').click()
    await app.window.getByTestId('agent-chat-permissions').selectOption('Read & Write')
    await app.window.getByTestId('agent-chat-reasoning-effort').selectOption('__default__')
    await app.window.getByTestId('agent-chat-apply').click()
    const selectedGif = testInfo.outputPath('selected-fixture.gif'), selectedPdf = testInfo.outputPath('selected-fixture.pdf')
    await fs.writeFile(selectedGif, server.gif); await fs.writeFile(selectedPdf, server.pdf)
    await app.electronApp.evaluate(({ dialog }, selected) => { dialog.showOpenDialog = (async () => ({ canceled: false, filePaths: [selected] })) as typeof dialog.showOpenDialog }, selectedGif)
    await app.window.getByTestId('composer-attach-button').click()
    await expect(app.window.getByTestId('composer-attachments-list')).toContainText(path.basename(selectedGif))
    await app.electronApp.evaluate(({ dialog }, selected) => { dialog.showOpenDialog = (async () => ({ canceled: false, filePaths: [selected] })) as typeof dialog.showOpenDialog }, selectedPdf)
    await app.window.getByTestId('agent-attach-documents').click()
    await expect(app.window.getByTestId('composer-attachments-list')).toContainText(path.basename(selectedPdf))
    await expect(app.window.getByTestId('agent-chat-api-transport')).toContainText('Anthropic Messages')
    const selected = (await snapshot())!
    expect(selected).toMatchObject({ provider: 'api', apiProfile: 'claude-connector-v1', apiTransport: 'anthropic-messages', apiClaudeConfig: savedConnection.claude, permissions: 'Read & Write' })
    expect(server.generationCount()).toBe(0)
    expect(posts()).toHaveLength(0)
    // Selection creates private copies; later sends must not reread these changed source files.
    await fs.writeFile(selectedGif, 'changed source'); await fs.writeFile(selectedPdf, 'changed source')
    await app.window.getByTestId('composer-input').fill(server.prompt)
    await app.window.getByTestId('composer-send-button').click()

    const approval = app.window.getByTestId(`provider-interaction-${server.ids.approval}`)
    await expect(approval).toHaveAttribute('data-state', 'pending')
    await expect(approval).toContainText('Fixture server write only')
    await expect(approval).toContainText(server.serverFilename)
    await expect(app.window.getByTestId('agent-session-status')).toHaveText('Waiting for your response')
    expect(posts()).toHaveLength(1)
    await expect(app.window.getByTestId('conversation-feed')).toContainText('Claude connector fixture —')
    expect(await fs.access(localSentinel).then(() => true, () => false)).toBe(false)
    await app.window.screenshot({ path: testInfo.outputPath('02-claude-native-approval.png'), fullPage: true })
    await approval.getByTestId(`claude-allow-${server.ids.approval}`).click()
    const question = app.window.getByTestId(`provider-interaction-${server.ids.question}`)
    await expect(question).toHaveAttribute('data-state', 'pending')
    await expect(approval).toHaveAttribute('data-state', 'resolved')
    await expect(approval.getByTestId(`claude-allow-${server.ids.approval}`)).toBeDisabled()
    expect(posts()).toHaveLength(2)
    await question.getByRole('radio', { name: /^Text file/ }).check()
    await question.getByRole('textbox', { name: 'Your answer', exact: true }).nth(1).fill(server.questionAnswers['Comment for fixture report?'])
    await app.window.screenshot({ path: testInfo.outputPath('03-claude-native-question.png'), fullPage: true })
    await question.getByRole('button', { name: 'Send answer', exact: true }).click()
    await expect.poll(async () => (await snapshot())?.lastTurn?.status, { timeout: 25_000 }).toBe('completed')
    await expect(question).toHaveAttribute('data-state', 'resolved')
    await expect(app.window.getByTestId('conversation-feed')).toContainText('completed with two immutable files — Ж ✓')
    expect(server.errors).toEqual([])
    expect(posts().map(item => item.path)).toEqual(['/v1/messages', `/v1/claude/approvals/${server.ids.approval}`, `/v1/claude/questions/${server.ids.question}`])
    expect(downloads()).toHaveLength(2)
    expect(await fs.access(localSentinel).then(() => true, () => false)).toBe(false)
    const completed = (await snapshot())!
    const nativeWrite = completed.feed.flatMap(message => message.tools ?? []).find(tool => tool.toolName === 'Write')!
    expect(nativeWrite).toMatchObject({ executor: 'provider', status: 'completed' })
    const references = completed.feed.flatMap(message => [...(message.artifacts ?? []), ...(message.tools ?? []).flatMap(tool => tool.artifacts ?? [])])
    expect(references).toHaveLength(2)
    for (let index = 0; index < references.length; index++) expect(references[index]).toMatchObject({ filename: 'fixture-report.txt', mime: 'text/plain', sha256: server.artifacts[index].metadata.sha256, revision: index + 1, ...(index ? { supersedesFileId: server.artifacts[0].metadata.id } : {}) })
    const inputImages = completed.feed.filter(message => message.role === 'user').flatMap(message => message.media ?? [])
    expect(inputImages).toHaveLength(1)
    expect(inputImages[0]).toMatchObject({ mime: 'image/gif', sha256: createHash('sha256').update(server.gif).digest('hex') })
    const image = app.window.getByTestId(`generated-image-${inputImages[0].id}`)
    await app.window.getByTestId(`generated-media-${inputImages[0].id}`).scrollIntoViewIfNeeded()
    await expect.poll(() => image.evaluate((node: HTMLImageElement) => node.complete && node.naturalWidth === 1)).toBe(true)
    const owner = { sessionId: completed.sessionId, runId: completed.runId }
    expect(await app.window.evaluate(ref => window.ziafAPI.agentSessions.listImages!(ref), owner)).toEqual([])
    expect(await app.window.evaluate(ref => window.ziafAPI.agentSessions.listDocuments!(ref), owner)).toEqual([])

    const assistant = app.window.locator('[data-testid^="assistant-message-"]').filter({ has: app.window.getByTestId(`generated-artifact-${references[1].id}`) })
    await assistant.locator('[data-testid^="tools-block-"]').getByRole('button').first().click()
    for (const ref of references) await expect(app.window.getByTestId(`generated-artifact-save-${ref.id}`)).toBeVisible()
    const savedFile = testInfo.outputPath('saved-fixture-revision-2.txt')
    await app.electronApp.evaluate(({ dialog }, filePath) => { dialog.showSaveDialog = (async () => ({ canceled: false, filePath })) as typeof dialog.showSaveDialog }, savedFile)
    await app.window.getByTestId(`generated-artifact-save-${references[1].id}`).click()
    await expect(app.window.getByTestId(`generated-artifact-${references[1].id}`).getByRole('status')).toHaveText('File saved!')
    expect(await fs.readFile(savedFile)).toEqual(server.artifacts[1].bytes)
    await app.window.screenshot({ path: testInfo.outputPath('04-claude-immutable-artifacts.png'), fullPage: true })

    const beforeRestart = (await snapshot())!, postsBeforeRestart = posts().length, downloadsBeforeRestart = downloads().length
    await app.restart(); await openTask()
    expect(await currentBuild()).toEqual(initialBuild)
    const replay = (await snapshot())!
    expect(replay.feed).toEqual(beforeRestart.feed)
    expect(replay.sessionId).toBe(beforeRestart.sessionId)
    expect(replay.apiClaudeConfig).toEqual(savedConnection.claude)
    await expect(app.window.getByTestId(`claude-allow-${server.ids.approval}`)).toBeDisabled()
    await expect(app.window.getByTestId(`provider-interaction-${server.ids.question}`).getByRole('button', { name: 'Send answer', exact: true })).toBeDisabled()
    const savedEarlier = testInfo.outputPath('saved-fixture-revision-1-after-restart.txt')
    await app.electronApp.evaluate(({ dialog }, filePath) => { dialog.showSaveDialog = (async () => ({ canceled: false, filePath })) as typeof dialog.showSaveDialog }, savedEarlier)
    await app.window.getByTestId(`generated-artifact-save-${references[0].id}`).click()
    await expect(app.window.getByTestId(`generated-artifact-${references[0].id}`).getByRole('status')).toHaveText('File saved!')
    expect(await fs.readFile(savedEarlier)).toEqual(server.artifacts[0].bytes)
    expect(posts()).toHaveLength(postsBeforeRestart)
    expect(downloads()).toHaveLength(downloadsBeforeRestart)
    expect(server.generationCount()).toBe(1)
    expect(server.errors).toEqual([])
    expect((await app.transcript()).filter(item => item.event === 'prompt' || item.event === 'pty-shell-start')).toEqual([])
    await app.window.screenshot({ path: testInfo.outputPath('05-claude-full-quit-history.png'), fullPage: true })
    await testInfo.attach('claude-connector-snapshot.json', { body: JSON.stringify(replay, null, 2), contentType: 'application/json' })
  } finally {
    await testInfo.attach('claude-loopback-transport.json', { body: JSON.stringify({ scope: 'Synthetic loopback Claude Connector v1 fixture; no native provider, credentials or external inference', generations: server.generationCount(), errors: server.errors, records: server.records }, null, 2), contentType: 'application/json' })
    await server.close()
  }
})
