import { test, expect } from './fixtures'

test.use({ providerFixture: 'claude' })

test('Claude native stream-json keeps approval, interrupt and later turns in one live session', async ({ app }, testInfo) => {
  test.setTimeout(120_000)
  const { window } = app
  const composer = window.getByTestId('composer-input')
  const feed = window.getByTestId('conversation-feed')
  const stop = window.getByTestId('composer-stop-button')
  const sendButton = window.getByTestId('composer-send-button')
  const open = () => window.getByRole('button', { name: 'E2E Workspace', exact: true }).click()
  const snapshot = () => window.evaluate(() => globalThis.window.ziafAPI.agentSessions.attach({ taskId: 'task-e2e', chatId: 'chat-main' }))
  const prompts = async (text: string) => (await app.transcript()).filter(entry => entry.event === 'prompt' && entry.text === text)
  const starts = async () => (await app.transcript()).filter(entry => entry.event === 'provider-start')
  const assistant = (text: string) => feed.locator('[data-testid^="assistant-message-"]').filter({ hasText: text })
  const users = (text: string) => feed.locator('[data-testid^="user-message-"]').filter({ hasText: text })
  const capture = async (name: string) => {
    const filename = testInfo.outputPath(name + '.png')
    await window.screenshot({ path: filename, fullPage: true })
    await testInfo.attach(name, { path: filename, contentType: 'image/png' })
  }
  const send = async (text: string) => {
    await composer.fill(text)
    await sendButton.click()
    await expect.poll(async () => (await prompts(text)).length).toBe(1)
  }

  await open()
  await expect(window.getByTestId('structured-claude-chat')).toBeVisible()
  await expect(stop).toHaveCount(0)
  expect(await starts()).toEqual([])
  await capture('01-claude-idle')
  await send('fixture-approval')
  const firstPrompt = (await prompts('fixture-approval'))[0]
  expect(firstPrompt.message).toBe(firstPrompt.threadId)
  await expect.poll(async () => (await snapshot())?.activeTurn?.status).toBe('waiting_for_approval')
  const first = (await snapshot())!
  const ref = { sessionId: first.sessionId, runId: first.runId }
  const approval = feed.locator('[data-testid^="approval-card-"]').filter({ hasText: 'Claude requests permission to use Bash' })
  await expect(approval).toHaveCount(1)
  await expect(users('fixture-approval')).toHaveCount(1)
  await capture('02-claude-permission-pending')
  await window.reload()
  await open()
  await expect(approval).toHaveCount(1)
  await expect(approval.locator('[data-testid^="approval-allow-"]')).toBeVisible()
  expect(await starts()).toHaveLength(1)
  expect((await snapshot())?.pendingApprovals).toHaveLength(1)
  await capture('03-claude-permission-replayed')
  await approval.locator('[data-testid^="approval-allow-"]').click()
  await expect.poll(async () => (await app.transcript()).filter(entry => entry.event === 'approval-response' && entry.decision === 'allow').length).toBe(1)
  await expect(assistant('Claude fixture approved: Привет 🌍')).toHaveCount(1)
  const tool = feed.getByTestId('tool-item-claude-tool-1')
  await expect(tool).toContainText('Bash')
  await tool.getByRole('button', { name: 'Output', exact: true }).click()
  await expect(tool.locator('pre')).toHaveText('fixture-claude-tool-output\n')
  await expect.poll(async () => (await snapshot())?.lastTurn?.status).toBe('completed')
  await expect(stop).toHaveCount(0)
  await expect(feed).not.toContainText('CLAUDE_FIXTURE_DIAGNOSTIC_ONLY')
  await capture('04-claude-tool-and-unicode')

  await send('fixture-interrupt')
  const longPrompt = (await prompts('fixture-interrupt'))[0]
  expect({ pid: longPrompt.pid, threadId: longPrompt.threadId, sessionInput: longPrompt.message }).toEqual({ pid: firstPrompt.pid, threadId: firstPrompt.threadId, sessionInput: firstPrompt.threadId })
  await expect(stop).toBeVisible()
  await expect(assistant('Claude fixture is still generating.')).toHaveCount(1)
  const activeTurnId = (await snapshot())!.activeTurn!.turnId
  if (process.platform === 'darwin') {
    await app.electronApp.evaluate(({ BrowserWindow, app }) => {
      BrowserWindow.getAllWindows().find(candidate => candidate.isVisible())!.close()
      app.emit('activate')
    })
    await expect.poll(() => app.electronApp.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().some(candidate => candidate.isVisible()))).toBe(true)
  }
  await stop.click()
  await expect.poll(async () => (await app.transcript()).filter(entry => entry.event === 'interrupt-ack').length).toBe(1)
  await expect.poll(async () => (await snapshot())?.activeTurn?.status).toBe('interrupting')
  expect((await snapshot())!.activeTurn!.turnId).toBe(activeTurnId)
  expect((await app.transcript()).filter(entry => entry.event === 'signal')).toEqual([])
  await composer.fill('fixture-after-stop')
  await expect(sendButton).toBeDisabled()
  expect(await prompts('fixture-after-stop')).toEqual([])
  await capture('05-claude-interrupt-ack-still-busy')
  await app.releaseClaude('finish-interrupt')
  await expect.poll(async () => (await snapshot())?.lastTurn?.status).toBe('interrupted')
  await expect(stop).toHaveCount(0)
  await expect(composer).toHaveValue('fixture-after-stop')
  await sendButton.click()
  await expect.poll(async () => (await prompts('fixture-after-stop')).length).toBe(1)
  const last = (await prompts('fixture-after-stop'))[0]
  expect({ pid: last.pid, threadId: last.threadId, sessionInput: last.message }).toEqual({ pid: firstPrompt.pid, threadId: firstPrompt.threadId, sessionInput: firstPrompt.threadId })
  await expect.poll(async () => (await snapshot())?.lastTurn?.status).toBe('completed')
  await expect(assistant('Claude fixture resumed on the same session. 🌍')).toHaveCount(1)
  await expect(assistant('Claude fixture resumed on the same session. 🌍')).toBeInViewport({ ratio: 1 })
  await capture('06-claude-next-turn-same-process')
  await window.reload()
  await open()
  for (const text of ['fixture-approval', 'fixture-interrupt', 'fixture-after-stop']) await expect(users(text)).toHaveCount(1)
  await expect(assistant('Claude fixture approved: Привет 🌍')).toHaveCount(1)
  await expect(assistant('Claude fixture resumed on the same session. 🌍')).toHaveCount(1)
  await expect(feed.locator('[data-testid^="approval-allow-"]')).toHaveCount(0)
  const replay = (await snapshot())!
  expect({ sessionId: replay.sessionId, runId: replay.runId }).toEqual(ref)
  expect(replay.provider).toBe('claude')
  expect(replay.sessionStatus).toBe('ready')
  expect(replay.activeTurn).toBeUndefined()
  expect(replay.pendingApprovals).toEqual([])
  await expect(assistant('Claude fixture resumed on the same session. 🌍')).toBeInViewport({ ratio: 1 })
  await capture('07-claude-history-replayed')
  const transcript = await app.transcript()
  expect(await starts()).toHaveLength(1)
  expect((await starts())[0].args).toEqual(['-p', '--input-format', 'stream-json', '--output-format', 'stream-json', '--include-partial-messages', '--verbose', '--permission-prompt-tool', 'stdio', '--permission-mode', 'plan', '--model', 'claude-fixture', '--session-id', firstPrompt.threadId])
  expect(transcript.filter(entry => entry.event === 'initialize-request')).toHaveLength(1)
  expect(transcript.filter(entry => entry.event === 'turn-result')).toHaveLength(3)
  expect(transcript.filter(entry => ['invalid-launch', 'protocol-error', 'pty-shell-start'].includes(entry.event || ''))).toEqual([])
  expect(new Set(transcript.filter(entry => entry.event === 'prompt').map(entry => entry.turnId)).size).toBe(3)
  await testInfo.attach('claude-session-snapshot.json', { body: JSON.stringify(replay, null, 2), contentType: 'application/json' })
  // fixtures.ts observes production Quit and checks this provider PID before fallback cleanup.
})
