import { test, expect } from './fixtures'

test.use({ providerFixture: 'codex' })

test('bottom configuration takes keyboard focus only after becoming visible and returns it on Escape', async ({ app }, testInfo) => {
  const { window } = app
  await window.getByRole('button', { name: 'E2E Workspace', exact: true }).click()
  const input = window.getByTestId('composer-input')
  const preset = window.getByTestId('composer-preset-button')
  const panel = window.getByTestId('agent-chat-settings')
  await input.fill('Unsent keyboard navigation draft')
  await window.keyboard.press('Tab')
  await expect(preset).toBeFocused()
  await window.keyboard.press('Enter')
  await expect(panel).toBeVisible()
  await expect(panel.getByRole('menuitemradio').first()).toBeFocused()
  await window.keyboard.press('Shift+Tab')
  await expect(window.getByTestId('composer-custom-option')).toBeFocused()
  await window.keyboard.press('Escape')
  await expect(panel).toHaveCount(0)
  await expect(preset).toBeFocused()

  // Mouse-opened menus also transfer focus, so Escape works immediately.
  await preset.click()
  await expect(panel.getByRole('menuitemradio').first()).toBeFocused()
  await window.keyboard.press('ArrowUp')
  await expect(window.getByTestId('composer-custom-option')).toBeFocused()
  await window.keyboard.press('Enter')
  await expect(panel).toHaveCount(0)
  await window.getByTestId('composer-model-button').click()
  await expect(window.getByTestId('agent-chat-model-catalog')).toBeFocused()
  await expect(window.getByTestId('agent-chat-model-catalog-status')).toContainText('model/list')
  await window.keyboard.press('Tab')
  await expect(window.getByTestId('agent-chat-model')).toBeFocused()
  await window.keyboard.press('Escape')
  await expect(panel).toHaveCount(0)
  await expect(window.getByTestId('composer-model-button')).toBeFocused()

  // Footer creation replaces its menu, so restoration needs a surviving trigger.
  const editor = window.getByTestId('preset-editor')
  for (const close of ['Escape', 'Cancel'] as const) {
    await preset.click()
    await window.getByTestId('composer-create-preset').click()
    await expect(editor.getByTestId('preset-name')).toBeFocused()
    if (close === 'Escape') await window.keyboard.press('Escape')
    else await editor.getByRole('button', { name: 'Cancel', exact: true }).click()
    await expect(editor).toHaveCount(0)
    await expect(preset).toBeFocused()
  }
  await preset.click()
  await window.getByTestId('composer-create-preset').click()
  await editor.getByTestId('preset-name').fill('Keyboard Created Preset')
  await editor.getByTestId('preset-save').click()
  await expect(editor).toHaveCount(0)
  await expect(preset).toContainText('Keyboard Created Preset')
  await expect(preset).toBeFocused()
  await expect(input).toHaveValue('Unsent keyboard navigation draft')
  expect((await app.transcript()).filter(entry => entry.event === 'prompt')).toHaveLength(0)
  await window.screenshot({ path: testInfo.outputPath('00-keyboard-configuration-returned-focus.png'), fullPage: true })
})

for (const initiation of ['keyboard', 'mouse'] as const) {
  test(`${initiation} Send keeps the next draft editable through delayed acknowledgement without stealing later focus`, async ({ app }, testInfo) => {
    test.setTimeout(90_000)
    const { window } = app
    await window.getByRole('button', { name: 'E2E Workspace', exact: true }).click()
    const input = window.getByTestId('composer-input')
    const prompts = async () => (await app.transcript()).filter(entry => entry.event === 'prompt')
    const snapshot = () => window.evaluate(() => globalThis.window.ziafAPI.agentSessions.attach({ taskId: 'task-e2e', chatId: 'chat-main' }))
    await input.fill('fixture-delayed-send')
    if (initiation === 'keyboard') await window.keyboard.press('Enter')
    else await window.getByTestId('composer-send-button').click()
    await expect.poll(async () => (await app.transcript()).some(entry => entry.event === 'barrier-waiting' && entry.barrier === 'accept-send')).toBe(true)
    await expect(input).toBeFocused()
    await expect(input).toBeEnabled()
    // keyboard.type deliberately cannot refocus the field, unlike locator.fill().
    await window.keyboard.press('ControlOrMeta+A')
    await window.keyboard.type('fixture-after-stop')
    await window.keyboard.press('Enter')
    await expect(input).toHaveValue('fixture-after-stop')
    expect(await prompts()).toHaveLength(1)
    await window.screenshot({ path: testInfo.outputPath('01-next-draft-before-send-ack.png'), fullPage: true })

    // A delayed ACK must not steal the user's newer focus or clear the newer draft.
    const logs = window.getByTestId('agent-cli-logs-toggle')
    await logs.click()
    await expect(logs).toBeFocused()
    await app.releaseCodex('accept-send')
    await expect.poll(async () => (await snapshot())?.lastTurn?.status).toBe('completed')
    await expect(logs).toBeFocused()
    await expect(input).toHaveValue('fixture-after-stop')
    expect(await prompts()).toHaveLength(1)
    await logs.click()
    await window.getByTestId('composer-send-button').click()
    await expect(input).toBeFocused()
    await expect.poll(async () => (await prompts()).length).toBe(2)
    await expect.poll(async () => (await snapshot())?.lastTurn?.status).toBe('completed')
    await expect(input).toHaveValue('')
    await window.keyboard.type('Unsent next draft')
    await expect(input).toHaveValue('Unsent next draft')
    expect((await prompts()).map(entry => entry.text)).toEqual(['fixture-delayed-send', 'fixture-after-stop'])
    await window.screenshot({ path: testInfo.outputPath('02-immediate-typing-after-completed-send.png'), fullPage: true })
  })
}

test('a delayed model change keeps focus on a newer Composer draft', async ({ app }, testInfo) => {
  test.setTimeout(90_000)
  const { window } = app
  const input = window.getByTestId('composer-input')
  const snapshot = () => window.evaluate(() => globalThis.window.ziafAPI.agentSessions.attach({ taskId: 'task-e2e', chatId: 'chat-main' }))
  await window.getByRole('button', { name: 'E2E Workspace', exact: true }).click()
  await input.fill('fixture-hello')
  await window.getByTestId('composer-send-button').click()
  await expect.poll(async () => (await snapshot())?.lastTurn?.status).toBe('completed')
  await window.getByTestId('composer-preset-button').click()
  await window.getByTestId('composer-custom-option').click()
  await window.getByTestId('composer-model-button').click()
  await window.getByTestId('agent-chat-model').fill('codex-delayed-config')
  await window.getByTestId('agent-chat-apply').click()
  await expect.poll(async () => (await app.transcript()).some(entry => entry.event === 'barrier-waiting' && entry.barrier === 'configure-session')).toBe(true)
  // The upward options surface covers the middle of the wide textarea.
  // Click its visible text-start area, as a user can, without force or DOM focus.
  await input.click({ position: { x: 14, y: 14 } })
  await window.keyboard.type('Draft entered during model change')
  await expect(input).toBeFocused()
  await app.releaseCodex('configure-session')
  await expect.poll(snapshot).toMatchObject({ sessionStatus: 'ready', model: 'codex-delayed-config' })
  await expect(input).toBeFocused()
  await window.keyboard.type(' and after acknowledgement')
  await expect(input).toHaveValue('Draft entered during model change and after acknowledgement')
  expect((await app.transcript()).filter(entry => entry.event === 'prompt').map(entry => entry.text)).toEqual(['fixture-hello'])
  await window.screenshot({ path: testInfo.outputPath('03-model-change-does-not-steal-draft-focus.png'), fullPage: true })
})
