import { writeFile } from 'node:fs/promises'
import { test, expect } from './fixtures'

test.use({ providerFixture: 'codex' })

test('bottom configuration preserves preset permissions and reasoning on the wire, draft and native resume', async ({ app }, testInfo) => {
  test.setTimeout(180_000)
  const savedName = 'E2E Custom Reasoning'
  const nextDraft = 'fixture-after-stop'
  const snapshot = () => app.window.evaluate(() => globalThis.window.ziafAPI.agentSessions.attach({ taskId: 'task-e2e', chatId: 'chat-main' }))
  const prompts = async () => (await app.transcript()).filter(entry => entry.event === 'prompt')
  const rpc = async (pid: number, method: string) => (await app.transcript()).filter(entry => entry.pid === pid && entry.event === 'rpc-in' && entry.rpc?.method === method)
  const openTask = () => app.window.getByRole('button', { name: 'E2E Workspace', exact: true }).click()
  const screenshot = async (name: string) => {
    const filename = testInfo.outputPath(`${name}.png`)
    await app.window.screenshot({ path: filename, fullPage: true })
    await testInfo.attach(name, { path: filename, contentType: 'image/png' })
  }

  // Use the ordinary preset editor before this task has a provider process.
  await app.window.getByRole('button', { name: 'Settings', exact: true }).first().click()
  await app.window.getByRole('button', { name: 'Presets', exact: true }).click()
  await app.window.getByRole('row').filter({ hasText: 'E2E Codex' }).getByTitle('Edit', { exact: true }).click()
  const editor = () => app.window.getByTestId('preset-editor')
  await expect(editor()).toBeVisible()
  await editor().getByTestId('preset-provider').selectOption('codex')
  await expect(editor().getByTestId('preset-model-catalog-status')).toContainText('model/list')
  await editor().getByTestId('preset-model-catalog').selectOption('codex-fixture')
  const presetEffort = editor().getByTestId('preset-reasoning-effort')
  await expect(presetEffort.locator('option[value="__default__"]')).toHaveCount(1)
  await expect(presetEffort.locator('option[value="none"]')).toHaveCount(1)
  await expect(presetEffort.locator('option[value="xhigh"]')).toHaveCount(0)
  await presetEffort.selectOption('none')
  await editor().getByTestId('preset-permissions').selectOption('Workspace write')
  await screenshot('01-preset-explicit-none-and-workspace-access')
  await editor().getByTestId('preset-save').click()
  await expect(editor()).toHaveCount(0)
  await expect.poll(async () => app.window.evaluate(async () => (await globalThis.window.ziafAPI.getPresets()).find(preset => preset.name === 'E2E Codex'))).toMatchObject({
    agent: 'Codex', model: 'codex-fixture', permissions: 'Workspace write', reasoningEffort: 'none',
  })
  expect(await prompts()).toHaveLength(0)

  await openTask()
  await expect(app.window.getByTestId('composer-preset-button')).toContainText('E2E Codex')
  await app.window.getByTestId('composer-input').fill('fixture-hello')
  await app.window.getByTestId('composer-send-button').click()
  await expect.poll(async () => (await prompts()).length).toBe(1)
  await expect.poll(async () => (await snapshot())?.lastTurn?.status).toBe('completed')
  const first = (await snapshot())!
  expect(first.activeTurn).toBeUndefined()
  expect(first).toMatchObject({ presetName: 'E2E Codex', model: 'codex-fixture', permissions: 'Workspace write', reasoningEffort: 'none' })
  const firstPrompt = (await prompts())[0]
  const firstLaunch = await rpc(firstPrompt.pid, 'thread/start')
  const firstTurn = await rpc(firstPrompt.pid, 'turn/start')
  expect(firstLaunch).toHaveLength(1)
  expect(firstLaunch[0].rpc?.params).toMatchObject({ model: 'codex-fixture', sandbox: 'workspace-write', approvalPolicy: 'on-request', config: { model_reasoning_effort: 'none' } })
  expect(firstTurn).toHaveLength(1)
  expect(firstTurn[0].rpc?.params).toMatchObject({ threadId: firstPrompt.threadId, effort: 'none' })

  // Edit one proposal across the Model and Options popovers, then apply once.
  await app.window.getByTestId('composer-input').fill(nextDraft)
  await app.window.getByTestId('composer-preset-button').click()
  await app.window.getByTestId('composer-custom-option').click()
  await app.window.getByTestId('composer-model-button').click()
  await expect(app.window.getByTestId('agent-chat-model-catalog-status')).toContainText('model/list')
  await app.window.getByTestId('agent-chat-model-catalog').selectOption('codex-fixture-next')
  await app.window.getByTestId('composer-options-button').click()
  const options = app.window.getByRole('dialog').filter({ has: app.window.getByTestId('agent-chat-options') })
  await expect(options).toBeVisible()
  const customEffort = options.getByTestId('agent-chat-reasoning-effort')
  await expect(customEffort.locator('option[value="__default__"]')).toHaveCount(1)
  await expect(customEffort.locator('option[value="xhigh"]')).toHaveCount(1)
  await expect(customEffort.locator('option[value="none"]')).toHaveCount(0)
  await customEffort.selectOption('xhigh')
  await options.getByTestId('agent-chat-permissions').selectOption('Read only')
  const bounds = await options.boundingBox()
  const trigger = await app.window.getByTestId('composer-options-button').boundingBox()
  const viewport = await app.window.evaluate(() => ({ width: window.innerWidth, height: window.innerHeight }))
  expect(bounds).not.toBeNull()
  expect(trigger).not.toBeNull()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.y).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(viewport.width)
  expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(viewport.height)
  expect(bounds!.y + bounds!.height, 'Options open above the Composer toolbar, without clipping').toBeLessThanOrEqual(trigger!.y)
  await screenshot('02-bottom-options-above-composer')
  expect((await snapshot())!).toMatchObject({ model: 'codex-fixture', reasoningEffort: 'none', permissions: 'Workspace write' })
  await options.getByTestId('agent-chat-apply').click()
  await expect.poll(snapshot).toMatchObject({ sessionStatus: 'ready', model: 'codex-fixture-next', permissions: 'Read only', reasoningEffort: 'xhigh' })
  await expect(options).toHaveCount(0)
  await expect(app.window.getByTestId('composer-input')).toHaveValue(nextDraft)
  expect(await prompts(), 'Configuration never sends the current draft').toHaveLength(1)

  // Creating a reusable preset stays in this conversation and carries all options.
  await app.window.getByTestId('composer-preset-button').click()
  await app.window.getByTestId('composer-create-preset').click()
  await expect(editor()).toBeVisible()
  await expect(editor().getByTestId('preset-name')).toHaveValue('')
  await expect(editor().getByTestId('preset-provider')).toHaveValue('codex')
  await expect(editor().getByTestId('preset-model')).toHaveValue('codex-fixture-next')
  await expect(editor().getByTestId('preset-permissions')).toHaveValue('Read only')
  await expect(editor().getByTestId('preset-reasoning-effort')).toHaveValue('xhigh')
  await editor().getByTestId('preset-name').fill(savedName)
  await screenshot('03-create-preset-with-retained-draft')
  await editor().getByTestId('preset-save').click()
  await expect(editor()).toHaveCount(0)
  await expect.poll(snapshot).toMatchObject({ sessionId: first.sessionId, sessionStatus: 'ready', presetName: savedName, model: 'codex-fixture-next', permissions: 'Read only', reasoningEffort: 'xhigh' })
  await expect(app.window.getByTestId('composer-preset-button')).toContainText(savedName)
  await expect(app.window.getByTestId('composer-input')).toHaveValue(nextDraft)
  const saved = await app.window.evaluate(async name => (await globalThis.window.ziafAPI.getPresets()).find(preset => preset.name === name), savedName)
  expect(saved).toMatchObject({ name: savedName, agent: 'Codex', model: 'codex-fixture-next', permissions: 'Read only', reasoningEffort: 'xhigh' })
  expect(await prompts()).toHaveLength(1)

  const beforeRestart = (await snapshot())!
  const electronPid = app.electronApp.process().pid
  await app.restart()
  expect(app.electronApp.process().pid).not.toBe(electronPid)
  await openTask()
  const restored = (await snapshot())!
  expect(restored).toMatchObject({ sessionId: first.sessionId, runId: beforeRestart.runId, presetName: savedName, model: 'codex-fixture-next', permissions: 'Read only', reasoningEffort: 'xhigh', resumeAvailable: true })
  await expect(app.window.getByTestId('composer-preset-button')).toContainText(savedName)
  await expect(app.window.getByTestId('composer-input')).toHaveValue(nextDraft)
  expect(await prompts()).toHaveLength(1)
  await app.window.getByTestId('agent-session-resume').click()
  await expect.poll(snapshot).toMatchObject({ sessionStatus: 'ready', model: 'codex-fixture-next', permissions: 'Read only', reasoningEffort: 'xhigh' })
  expect((await snapshot())!.runId).not.toBe(beforeRestart.runId)
  expect(await prompts(), 'Resume does not replay input or submit the retained draft').toHaveLength(1)
  await expect(app.window.getByTestId('composer-input')).toHaveValue(nextDraft)
  await app.window.getByTestId('composer-send-button').click()
  await expect.poll(async () => (await prompts()).length).toBe(2)
  await expect.poll(async () => (await snapshot())?.lastTurn?.status).toBe('completed')
  const secondPrompt = (await prompts())[1]
  expect(secondPrompt.text).toBe(nextDraft)
  expect(secondPrompt.threadId).toBe(firstPrompt.threadId)
  expect(secondPrompt.pid).not.toBe(firstPrompt.pid)
  const resumeLaunch = await rpc(secondPrompt.pid, 'thread/resume')
  const secondTurn = await rpc(secondPrompt.pid, 'turn/start')
  expect(resumeLaunch).toHaveLength(1)
  expect(resumeLaunch[0].rpc?.params).toMatchObject({ threadId: firstPrompt.threadId, model: 'codex-fixture-next', sandbox: 'read-only', approvalPolicy: 'on-request', config: { model_reasoning_effort: 'xhigh' } })
  expect(secondTurn).toHaveLength(1)
  expect(secondTurn[0].rpc?.params).toMatchObject({ threadId: firstPrompt.threadId, effort: 'xhigh' })
  const feed = app.window.getByTestId('conversation-feed')
  await expect(feed.locator('[data-testid^="user-message-"]')).toHaveCount(2)
  await expect(feed.locator('[data-testid^="assistant-message-"]')).toHaveCount(2)
  await expect(feed.locator('[data-testid^="assistant-message-"]').last()).toBeInViewport({ ratio: 1 })
  await screenshot('04-restored-preset-and-two-turn-history')

  // Default is an explicit reset, distinct from inheriting the saved xhigh.
  // Codex rejects a null config value: resume omits that key and each new turn
  // receives this model's advertised default instead of its previous override.
  const afterSecondTurn = (await snapshot())!
  await app.window.getByTestId('composer-input').fill('fixture-switch')
  await app.window.getByTestId('composer-preset-button').click()
  await app.window.getByTestId('composer-custom-option').click()
  await app.window.getByTestId('composer-options-button').click()
  await app.window.getByTestId('agent-chat-reasoning-effort').selectOption('__default__')
  await app.window.getByTestId('agent-chat-apply').click()
  await expect.poll(snapshot).toMatchObject({ sessionId: first.sessionId, sessionStatus: 'ready', model: 'codex-fixture-next', permissions: 'Read only', reasoningEffort: null })
  const defaultSelection = (await snapshot())!
  expect(defaultSelection.runId).not.toBe(afterSecondTurn.runId)
  await expect(app.window.getByTestId('composer-input')).toHaveValue('fixture-switch')
  expect(await prompts(), 'Default reset never submits a draft or replays previous input').toHaveLength(2)
  await app.window.getByTestId('composer-send-button').click()
  await expect.poll(async () => (await prompts()).length).toBe(3)
  await expect.poll(async () => (await snapshot())?.lastTurn?.status).toBe('completed')
  const thirdPrompt = (await prompts())[2]
  expect(thirdPrompt.text).toBe('fixture-switch')
  expect(thirdPrompt.threadId).toBe(firstPrompt.threadId)
  expect(thirdPrompt.pid).not.toBe(secondPrompt.pid)
  const defaultLaunch = await rpc(thirdPrompt.pid, 'thread/resume')
  const defaultTurn = await rpc(thirdPrompt.pid, 'turn/start')
  const defaultModelQueries = await rpc(thirdPrompt.pid, 'model/list')
  expect(defaultLaunch).toHaveLength(1)
  expect(defaultLaunch[0].rpc?.params).toMatchObject({ threadId: firstPrompt.threadId, model: 'codex-fixture-next', sandbox: 'read-only', approvalPolicy: 'on-request' })
  expect(defaultLaunch[0].rpc?.params?.config ?? {}, 'No null config and no old xhigh override on native resume').not.toHaveProperty('model_reasoning_effort')
  expect(defaultModelQueries.length).toBeGreaterThan(0)
  for (const query of defaultModelQueries) expect(query.rpc?.params).toMatchObject({ includeHidden: true })
  expect(defaultTurn).toHaveLength(1)
  expect(defaultTurn[0].rpc?.params).toMatchObject({ threadId: firstPrompt.threadId, effort: 'high' })
  expect((await snapshot())!).toMatchObject({ reasoningEffort: null, permissions: 'Read only' })
  await expect(feed.locator('[data-testid^="user-message-"]')).toHaveCount(3)
  await expect(feed.locator('[data-testid^="assistant-message-"]')).toHaveCount(3)
  await expect(feed.locator('[data-testid^="assistant-message-"]').last()).toBeInViewport({ ratio: 1 })
  await screenshot('05-provider-default-reset-with-three-turn-history')
  const transcript = await app.transcript()
  expect(transcript.filter(entry => entry.event === 'rpc-in' && entry.rpc?.method === 'turn/start')).toHaveLength(3)
  expect(transcript.filter(entry => entry.event === 'prompt').map(entry => entry.text)).toEqual(['fixture-hello', nextDraft, 'fixture-switch'])
  expect(transcript.filter(entry => ['invalid-launch', 'invalid-resume', 'protocol-error', 'pty-shell-start'].includes(entry.event || ''))).toEqual([])
  await writeFile(testInfo.outputPath('configuration-receipt.json'), JSON.stringify({
    first, savedPreset: saved, beforeRestart, restored, afterSecondTurn, defaultSelection, final: await snapshot(), popover: { bounds, trigger, viewport },
    providerPrompts: [firstPrompt, secondPrompt, thirdPrompt], wire: { firstLaunch, firstTurn, resumeLaunch, secondTurn, defaultLaunch, defaultModelQueries, defaultTurn },
  }, null, 2) + '\n')
  // The shared fixture checks normal Quit, every provider/catalog PID, and fallback cleanup.
})
