import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { test, expect } from './fixtures'

test.use({ providerFixture: 'codex' })

test('Git UI commits selected files, shows a failed push, merges locally and retains real receipts after Quit', async ({ app }, testInfo) => {
  test.setTimeout(180000)
  const source = testInfo.outputPath('profile', 'project', 'repo')
  const worktree = testInfo.outputPath('profile', 'project', 'worktrees', 'task-e2e')
  const git = async (cwd: string, args: string[]) => (await promisify(execFile)('/usr/bin/git', ['-C', cwd, ...args])).stdout.trim()
  await git(source, ['config', 'user.name', 'ZIAForge fixture'])
  await git(source, ['config', 'user.email', 'fixture@ziaforge.invalid'])
  await git(source, ['config', 'commit.gpgsign', 'false'])
  await git(source, ['remote', 'add', 'origin', testInfo.outputPath('missing-remote.git')])
  await writeFile(path.join(worktree, 'selected.txt'), 'reviewed content\n')
  await writeFile(path.join(worktree, 'unrelated.txt'), 'preserve this\n')
  await app.window.getByRole('button', { name: 'E2E Workspace', exact: true }).click()
  await app.window.getByTestId('tab-btn-git').click()
  const panel = app.window.getByTestId('git-panel')
  await expect(panel.getByTestId('git-branch')).toContainText('e2e')
  await panel.getByRole('button', { name: 'View selected.txt', exact: true }).click()
  await expect(panel.getByTestId('git-diff')).toContainText('reviewed content')
  await panel.getByLabel('??selected.txt').check()
  await panel.getByTestId('git-commit-message').fill('UI selected-file commit')
  await panel.getByTestId('git-commit').click()
  await expect.poll(() => git(worktree, ['log', '-1', '--format=%s'])).toBe('UI selected-file commit')
  expect(await git(worktree, ['status', '--porcelain'])).toContain('?? unrelated.txt')
  expect(await readFile(path.join(worktree, 'unrelated.txt'), 'utf8')).toBe('preserve this\n')
  await app.window.screenshot({ path: testInfo.outputPath('01-real-selected-commit.png'), fullPage: true })
  await panel.getByRole('button', { name: 'Push', exact: true }).click()
  await panel.getByTestId('git-proposal').getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect(panel.getByRole('alert')).toContainText(/repository|remote|access|failed/i)
  await expect(panel.locator('summary').filter({ hasText: 'push · failed' })).toBeVisible()
  await app.window.screenshot({ path: testInfo.outputPath('02-push-failure-retained.png'), fullPage: true })

  await panel.getByLabel('??unrelated.txt').check()
  await panel.getByTestId('git-commit-message').fill('Preserved file explicitly selected')
  await panel.getByTestId('git-commit').click()
  await expect(panel.locator('summary').filter({ hasText: 'commit · succeeded' })).toHaveCount(2, { timeout: 45000 })
  await expect(panel.getByTestId('git-commit-message')).toBeEnabled()
  expect(await git(worktree, ['status', '--porcelain'])).toBe('')
  await panel.getByRole('button', { name: 'Review merge', exact: true }).click()
  await panel.getByTestId('git-proposal').getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect(panel.locator('summary').filter({ hasText: 'merge · succeeded' })).toBeVisible({ timeout: 30000 })
  expect(await git(source, ['show', 'main:selected.txt'])).toBe('reviewed content')
  const before = await app.window.evaluate(() => window.ziafAPI.git.status({ taskId: 'task-e2e' }))
  await app.restart()
  await app.window.getByRole('button', { name: 'E2E Workspace', exact: true }).click()
  await app.window.getByTestId('tab-btn-git').click()
  const replay = await app.window.evaluate(() => window.ziafAPI.git.status({ taskId: 'task-e2e' }))
  expect(replay.head).toBe(before.head)
  expect(replay.receipts).toEqual(before.receipts)
  await app.window.screenshot({ path: testInfo.outputPath('03-git-receipts-after-restart.png'), fullPage: true })
})
