import fs from 'node:fs/promises'
import { createHash } from 'node:crypto'
import { test, expect } from './fixtures'
import { startGrokFixture } from './fixtures/grok-server'

test.use({ providerFixture: 'codex' })

test('Grok profile keeps native questions and approvals explicit, retains images and stops without replay after full Quit', async ({ app }, testInfo) => {
  test.setTimeout(180_000)
  const server = await startGrokFixture()
  const snapshot = () => app.window.evaluate(() => window.ziafAPI.agentSessions.attach({ taskId: 'task-e2e', chatId: 'chat-main' }))
  const openTask = () => app.window.getByRole('button', { name: 'E2E Workspace', exact: true }).click()
  const postCount = () => server.records.filter(item => item.method === 'POST').length
  try {
    await app.window.getByRole('button', { name: 'Connections', exact: true }).first().click()
    await app.window.getByTestId('api-connection-name').fill('Local Grok fixture')
    await app.window.getByTestId('api-connection-url').fill(server.baseUrl)
    await app.window.getByTestId('api-connection-model').fill('grok-fixture')
    await app.window.getByTestId('api-connection-transport').selectOption('responses')
    await app.window.getByTestId('api-connection-profile').selectOption('grok-connector-v1')
    await app.window.getByTestId('api-grok-max-turns').fill('9')
    await app.window.getByTestId('api-connection-save').click()
    await expect(app.window.getByTestId('api-connection-saved')).toBeVisible()
    const [connection] = await app.window.evaluate(() => window.ziafAPI.apiConnections.list())
    expect(connection).toMatchObject({ transport: 'responses', profile: 'grok-connector-v1', hasApiKey: false, grok: { maxTurns: 9 } })
    await app.window.getByTestId(`api-grok-inspect-${connection.id}`).click()
    await expect(app.window.getByTestId('api-grok-credit-usage')).toHaveText('No data')
    await expect(app.window.getByTestId('api-grok-capabilities')).toContainText('Video is not enabled')
    await app.window.getByTestId(`api-connection-${connection.id}`).getByRole('button', { name: 'Edit', exact: true }).click()
    await app.window.getByTestId('api-grok-context-window').selectOption('32000')
    await app.window.getByTestId('api-connection-save').click()
    await expect(app.window.getByTestId('api-connection-saved')).toBeVisible()
    await app.window.screenshot({ path: testInfo.outputPath('01-grok-connection.png'), fullPage: true })

    await openTask()
    // Change the unopened fixture chat using ordinary controls; no CLI bootstrap prompt.
    await app.window.getByTestId('composer-preset-button').click()
    await app.window.getByTestId('composer-custom-option').click()
    await app.window.getByTestId('composer-provider-button').click()
    await app.window.getByTestId('agent-chat-provider').selectOption('api')
    await app.window.getByTestId('agent-chat-api-connection').selectOption(connection.id)
    await app.window.getByTestId('agent-chat-apply').click()
    expect(server.generationCount()).toBe(0)
    const selectedPath = testInfo.outputPath('selected-image.png')
    await fs.writeFile(selectedPath, server.png)
    await app.electronApp.evaluate(({ dialog }, selected) => { dialog.showOpenDialog = (async () => ({ canceled: false, filePaths: [selected] })) as typeof dialog.showOpenDialog }, selectedPath)
    await app.window.getByTestId('composer-attach-button').click()
    await expect(app.window.getByTestId('composer-attachments-list')).toContainText('selected-image.png')
    await expect(app.window.getByTestId('agent-chat-api-transport')).toContainText('Grok Connector v1')
    expect(server.generationCount()).toBe(0)
    await app.window.getByTestId('composer-send-button').click()
    const question = app.window.getByTestId(`provider-interaction-${server.ids.question}`)
    await expect(question).toBeVisible()
    expect(postCount()).toBe(1)
    await expect(app.window.getByTestId('agent-session-status')).toHaveText('Waiting for your response')
    await expect(app.window.getByTestId('composer-process-status')).toHaveText('Waiting for your response')
    await expect(app.window.getByTestId('composer-process-status')).toHaveAttribute('data-state', 'response')
    await question.getByRole('checkbox', { name: 'Linux Desktop A' }).check()
    await question.getByRole('checkbox', { name: 'Windows Desktop B' }).check()
    await question.getByRole('radio', { name: 'Other — write your answer' }).check()
    await question.getByRole('textbox', { name: 'Your answer' }).fill('Exact written answer — Ж')
    await app.window.screenshot({ path: testInfo.outputPath('02-native-question.png'), fullPage: true })
    await question.getByRole('button', { name: 'Send answer', exact: true }).click()
    const reject = app.window.getByTestId(`provider-interaction-${server.ids.reject}`)
    await expect(reject).toBeVisible(); expect(postCount()).toBe(2)
    await reject.getByRole('button', { name: 'Reject this operation once', exact: true }).click()
    const allow = app.window.getByTestId(`provider-interaction-${server.ids.allow}`)
    await expect(allow).toBeVisible(); expect(postCount()).toBe(3)
    await expect(app.window.getByTestId('agent-session-status')).toHaveText('Waiting for your response')
    await expect(app.window.getByTestId('composer-process-status')).toHaveText('Waiting for your response')
    await expect(app.window.getByTestId('composer-process-status')).toHaveAttribute('data-state', 'response')
    await app.window.screenshot({ path: testInfo.outputPath('03-native-permission.png'), fullPage: true })
    await allow.getByRole('button', { name: 'Allow this operation once', exact: true }).click()
    await expect.poll(async () => (await snapshot())?.lastTurn?.status, { timeout: 20_000 }).toBe('completed')
    expect(postCount()).toBe(4); expect(server.generationCount()).toBe(1); expect(server.errors).toEqual([])
    const completed = (await snapshot())!
    const input = completed.feed.flatMap(message => message.role === 'user' ? message.media ?? [] : [])
    const generated = completed.feed.flatMap(message => (message.tools ?? []).flatMap(tool => tool.media ?? []))
    expect(input).toHaveLength(1); expect(generated).toHaveLength(1)
    expect(input[0].sha256).toBe(server.sha256); expect(generated[0].sha256).toBe(server.sha256)
    expect(await app.window.evaluate(ref => window.ziafAPI.agentSessions.listImages!(ref), { sessionId: completed.sessionId, runId: completed.runId })).toEqual([])
    for (const media of [input[0], generated[0]]) {
      const raster = app.window.getByTestId(`generated-image-${media.id}`)
      await app.window.getByTestId(`generated-media-${media.id}`).scrollIntoViewIfNeeded()
      await expect.poll(() => raster.evaluate((node: HTMLImageElement) => node.complete && node.naturalWidth > 0)).toBe(true)
      await app.window.getByTestId(`generated-media-open-${media.id}`).click()
      await app.window.getByTestId('image-viewer-actual-size').click()
      await expect(app.window.getByTestId('image-viewer-scale')).toHaveText('100%')
      await app.window.getByTestId('image-viewer-zoom-in').click()
      await expect(app.window.getByTestId('image-viewer-scale')).toHaveText('125%')
      await app.window.getByTestId('image-viewer-close').click()
    }
    const saved = testInfo.outputPath('saved-input-image.png')
    await app.electronApp.evaluate(({ dialog }, filePath) => { dialog.showSaveDialog = (async () => ({ canceled: false, filePath })) as typeof dialog.showSaveDialog }, saved)
    await app.window.getByTestId(`generated-media-save-${input[0].id}`).click()
    await expect(app.window.getByTestId(`generated-media-${input[0].id}`).getByRole('status')).toHaveText('Image saved')
    expect(createHash('sha256').update(await fs.readFile(saved)).digest('hex')).toBe(server.sha256)
    await app.window.screenshot({ path: testInfo.outputPath('04-input-and-generated-history.png'), fullPage: true })

    await app.window.getByTestId('composer-input').fill('Wait for Stop without answering this question')
    await app.window.getByTestId('composer-send-button').click()
    await expect(app.window.getByTestId(`provider-interaction-${server.ids.cancelledQuestion}`)).toBeVisible()
    await app.window.getByTestId('composer-stop-button').click()
    await expect.poll(async () => (await snapshot())?.lastTurn?.status, { timeout: 20_000 }).toBe('interrupted')
    expect(server.records.filter(item => item.path.endsWith('/cancel'))).toHaveLength(1)
    const beforeRestart = (await snapshot())!, requestsBefore = postCount()
    await app.restart(); await openTask()
    const replay = (await snapshot())!
    expect(replay.feed).toEqual(beforeRestart.feed)
    expect(replay.sessionId).toBe(beforeRestart.sessionId)
    expect(replay.apiProfile).toBe('grok-connector-v1')
    await expect(app.window.getByTestId(`provider-interaction-${server.ids.allow}`).getByRole('button', { name: 'Allow this operation once' })).toBeDisabled()
    await expect(app.window.getByTestId(`provider-interaction-${server.ids.cancelledQuestion}`).getByRole('button', { name: 'Send answer' })).toHaveCount(0)
    await app.window.getByTestId(`generated-media-${input[0].id}`).scrollIntoViewIfNeeded()
    await app.window.getByTestId(`generated-media-open-${input[0].id}`).click()
    await expect(app.window.getByTestId('image-viewer')).toBeVisible()
    await app.window.getByTestId('image-viewer-close').click()
    expect(postCount()).toBe(requestsBefore); expect(server.generationCount()).toBe(2)
    expect(server.errors).toEqual([])
    expect((await app.transcript()).filter(item => item.event === 'prompt' || item.event === 'pty-shell-start')).toEqual([])
    await app.window.screenshot({ path: testInfo.outputPath('05-full-quit-replay.png'), fullPage: true })
    await testInfo.attach('grok-snapshot.json', { body: JSON.stringify(replay, null, 2), contentType: 'application/json' })
  } finally {
    await testInfo.attach('grok-local-transport.json', { body: JSON.stringify({ scope: 'Local deterministic Grok v1 fixture; no credentials or external inference', generations: server.generationCount(), errors: server.errors, records: server.records }, null, 2), contentType: 'application/json' })
    await server.close()
  }
})
