import englishHelp from '../../docs/help/en.json'
import { helpSourceSha256 } from '../../src/components/helpSource.generated'
import { METHOD_CHANNELS, assertCommandScope } from './ControlPolicy'

/** Argument tuples match the IPC APIs. This describes authority; it never grants it. */
interface CommandSignature { args: string; result: string; notes?: string }
const signature = (args: string, result: string, notes?: string): CommandSignature => ({ args, result, ...(notes ? { notes } : {}) })
const signatures: Record<string, CommandSignature> = {
  'updates.status': signature('[]', 'UpdateStatus', 'Status only. Updater configuration, checking, download and installation require local owner settings.'),
  'control.status': signature('[]', 'ControlStatus', 'Credentials are not returned to remote callers.'),
  'control.assistantState': signature('[]', 'AssistantState'),
  'control.assistantSend': signature('[{text:string,instanceId?:string}]', 'AssistantState', 'Top-level remote/UI dispatch only; nested architect dispatch is forbidden.'),
  'control.assistantStop': signature('[]', 'void'),
  'control.execute': signature('[ControlRequest]', 'unknown', 'Top-level remote/UI dispatch only; execute cannot recursively call execute.'),
  'control.remote': signature('[{instanceId:string,request:ControlRequest}]', 'unknown', 'Use an existing configured instance ID. Both local and destination scopes apply.'),
  getRepositories: signature('[]', 'Repository[]'),
  saveRepositories: signature('[Repository[]]', 'void', 'Fetch the full current list first. Existing paths/grants cannot be changed or forged; removal has lifecycle consequences.'),
  getTasks: signature('[]', 'StoredTask[]'),
  createTask: signature('[CreateTaskConfig]', 'StoredTask', 'model is a preset name; providerModel is a native model ID. Use createRequestId for durable creation retry. Default to explicit manual policy when authorization is unclear.'),
  startTask: signature('[taskId:string]', 'OperationResult & {worktreePath?:string} | void', 'Prepares/starts the stored task; not a substitute for workflow gate approval.'),
  lookupCodeStart: signature('[{repoId:string,createRequestId:string}]', 'StoredTask | null'),
  lookupWorkStart: signature('[{createRequestId:string}]', 'StoredTask | null'),
  getSettings: signature('[]', 'Settings'),
  saveSettings: signature('[Settings]', 'void', 'Read-modify-write the complete object. Changing globalWorkspacePath requires local owner settings.'),
  getAppVersion: signature('[]', '{version:string,isDev:boolean,fullVersion:string}'),
  getPresets: signature('[]', 'Preset[]'),
  savePresets: signature('[Preset[]]', 'void', 'Read-modify-write the full list. Existing sessions keep frozen configuration until explicit reconfigure.'),
  getChatHistory: signature('[taskId:string]', 'ChatHistory'),
  saveChatHistory: signature('[ChatHistory & {taskId:string}]', 'OperationResult', 'Task-scoped renderer tabs/drafts; does not author or replace provider journal evidence.'),
  registerProject: signature('[{repoPath:string,projectName:string}]', 'OperationResult & {projectPath?:string,repoPath?:string,projectName?:string,projectId?:string}', 'Remote registration is restricted to the configured workspace root.'),
  getProjectBranches: signature('[{repoPath:string}]', 'string[]'),
  listProjectFiles: signature('[{projectPath:string}]', 'ProjectFile[]', 'Only registered/authorized paths.'),
  readFile: signature('[{filePath:string}]', 'string', 'Only registered/authorized paths. Prefer editorRead for large or version-sensitive edits.'),
  writeFile: signature('[{filePath:string,content:string}]', '{success:boolean}', 'Only authorized paths. Prefer editorSave for conflict-aware editing.'),
  createDirectory: signature('[{dirPath:string}]', '{success:boolean}', 'Only authorized paths.'),
  getAgentModels: signature('[{agent:string}]', 'string[]'),
  getAgentModelCatalog: signature('[{agent:string,apiConnectionId?:string}]', 'AgentModelCatalog', 'Use returned supported reasoning efforts/defaults; never invent a supported level.'),
  listWorkspaceFolders: signature('[]', 'string[]'),
  createWorkspaceFolder: signature('[name:string]', 'OperationResult & {folderPath?:string}'),
  deleteProjectFiles: signature('[{repoId:string,deleteWorkspaceDir:boolean,deleteSourceDir:boolean}]', 'OperationResult', 'Destructive. Requires explicit authorization for each selected directory; owned sessions must be stopped by the backend.'),
  openExternal: signature('[url:string]', 'void', 'Backend URL policy still applies.'),
  'apiConnections.list': signature('[]', 'ApiConnection[]', 'Returns hasApiKey, never the key.'),
  'apiConnections.save': signature('[{id?:string,name:string,baseUrl:string,model:string,enabled:boolean,apiKey?:string}]', 'ApiConnection', 'HTTPS or loopback HTTP only. Omitted apiKey preserves it; empty apiKey removes it. Never echo credentials.'),
  'apiConnections.inspect': signature('[{id:string}]', 'GrokConnectorInspection', 'Read-only Grok capability/model/usage discovery. Never returns credentials or account identifiers; discovery is not inference acceptance.'),
  'apiConnections.remove': signature('[{id:string}]', 'void'),
  'git.prepare': signature('[{taskId:string}]', 'GitTaskBinding'),
  'git.status': signature('[{taskId:string}]', 'GitStatus', 'Returns current head, fingerprint, local branches with heads, remotes, conflicts and operation receipts.'),
  'git.diff': signature('[{taskId:string,scope:"working"|"staged"|"base",path?:string}]', 'GitDiff'),
  'git.commit': signature('[{taskId:string,operationId:string,expectedHead:string,expectedStatusFingerprint:string,message:string,paths:string[]}]', 'GitOperationReceipt', 'Explicit reviewed paths and exact current status fingerprint; preserve unrelated changes.'),
  'git.push': signature('[{taskId:string,operationId:string,expectedHead:string,remote:string}]', 'GitOperationReceipt', 'Separate explicit push authorization; select a remote returned by git.status.'),
  'git.merge': signature('[{taskId:string,operationId:string,expectedHead:string,targetBranch:string,expectedTargetHead:string}]', 'GitOperationReceipt', 'Separate explicit merge authorization; bind both branch heads from current status.'),
  'git.removeWorktree': signature('[{taskId:string,operationId:string,expectedHead:string,expectedStatusFingerprint:string}]', 'GitOperationReceipt', 'Explicit removal authorization; backend refuses unsafe dirty/attached workspaces.'),
  'workflows.get': signature('[{taskId:string}]', 'WorkflowSnapshot | null'),
  'workflows.save': signature('[{taskId:string,expectedRevision:number,plan:WorkflowPlan}]', 'WorkflowSnapshot', 'Use current snapshot revision and a full edited plan; immutable completed proof cannot be rewritten.'),
  'workflows.start': signature('[{taskId:string,revision:number,commandId:string}]', 'WorkflowSnapshot', 'revision, not expectedRevision. Start does not accept a pending document/plan/review gate.'),
  'workflows.pause': signature('[{taskId:string}]', 'WorkflowSnapshot'),
  'workflows.discuss': signature('[{taskId:string,revision:number,commandId:string,text:string,stepId?:string,phase?:"discovery"|"investigation"|"requirements"|"specification"|"planning"|"implementation",artifactEdits?:{artifactId:string,expectedSha256:string,content:string}[]}]', 'WorkflowSnapshot', 'Discussion is not acceptance. Omit stepId/phase for the current stage. Active work is controlled-paused/drained before a new turn; rewinds invalidate dependent future approvals.'),
  'workflows.respond': signature('[{taskId:string,revision:number,gateId:string,commandId:string,action:"answer"|"approve"|"changes"|"cancel"|"rereview",text?:string,proposedSteps?:CodeProposedStep[]}]', 'WorkflowSnapshot', 'Use current codeFlow.pending.id and human-authorized action. proposedSteps only for approve of plan, in desired order. Explicit completed native Multi rereview uses gateId="completed-review" and action="rereview". Do not manufacture human consent.'),
  'workflows.readArtifact': signature('[{taskId:string,artifactId:string}]', '{name:string,content:string,sha256:string,version:number}'),
  'workFlows.get': signature('[{taskId:string}]', 'WorkFlowSnapshot | null'),
  'workFlows.save': signature('[{taskId:string,expectedRevision:number,definition:WorkFlowDefinition}]', 'WorkFlowSnapshot', 'After invocations, only allowed policy changes can be saved; role context stays frozen.'),
  'workFlows.start': signature('[{taskId:string,revision:number,commandId:string}]', 'WorkFlowSnapshot'),
  'workFlows.pause': signature('[{taskId:string}]', 'WorkFlowSnapshot'),
  'workFlows.respond': signature('[{taskId:string,runId:string,revision:number,gateId:string,commandId:string,action:WorkGateAction,text?:string,answers?:{questionId:string,text:string}[]}]', 'WorkFlowSnapshot', 'Use snapshot.runId, revision, pending.id and ONLY actions offered by pending.actions. Preserve question IDs. Artifact/plan approvals require human authorization.'),
  'workFlows.followUp': signature('[{taskId:string,runId:string,revision:number,commandId:string,artifactId?:string,text:string}]', 'WorkFlowSnapshot', 'Explicit follow-up to the current completed result; backend selects small continuation versus a new worker round.'),
  'workFlows.readArtifact': signature('[{taskId:string,artifactId:string}]', '{name:string,content:string,sha256:string,version:number}', 'Text only; binary artifacts remain available through openArtifact.'),
  'workFlows.openArtifact': signature('[{taskId:string,artifactId:string}]', 'void', 'Opens/reveals a verified immutable artifact copy, not an arbitrary path.'),
  'agentSessions.create': signature('[{taskId:string,chatId:string,presetName?:string,provider?:Provider,model?:string,apiConnectionId?:string,requestId?:string,reasoningEffort?:string|null,permissions?:string}]', 'AgentSessionSnapshot', 'Paths/binary/env are backend-resolved. Empty presetName selects Custom. Generic calls cannot mutate workflow-owned chats.'),
  'agentSessions.resume': signature('[SessionRef]', 'AgentSessionSnapshot', 'Explicit native/context resume; returns a new current ref. Pending queue stays paused.'),
  'agentSessions.reconfigure': signature('[SessionRef & {presetName:string,provider?:Provider,model?:string,apiConnectionId?:string,requestId?:string,reasoningEffort?:string|null,permissions?:string}]', 'AgentSessionSnapshot', 'Idle only, no pending queue. Preserves visible history and explicitly changes the frozen launch context.'),
  'agentSessions.attach': signature('[{taskId:string,chatId:string}]', 'AgentSessionSnapshot | null'),
  'agentSessions.snapshot': signature('[SessionRef]', 'AgentSessionSnapshot'),
  'agentSessions.send': signature('[SessionRef & {clientMessageId:string,text:string}]', 'AgentSendReceipt', 'Use a stable clientMessageId. Receipt/transport ACK is not turn completion; inspect snapshot.lastTurn. Unknown delivery must not be resent with a new ID.'),
  'agentSessions.queue': signature('[SessionRef & {clientMessageId:string,text:string}]', 'AgentSessionSnapshot', 'Acknowledges durable queue acceptance, not provider completion. Unknown deliveries are never automatically replayed.'),
  'agentSessions.setQueuePaused': signature('[SessionRef & {paused:boolean}]', 'AgentSessionSnapshot', 'Explicit continuation after restart is required; uncertain items must be resolved/dismissed first.'),
  'agentSessions.cancelQueued': signature('[SessionRef & {clientMessageId:string}]', 'AgentSessionSnapshot', 'Dismisses the queued/uncertain record; does not undo a delivered provider request.'),
  'agentSessions.interrupt': signature('[SessionRef & {turnId:string}]', 'void', 'Use current activeTurn.turnId and interruptTurn capability; ACK does not prove cleanup/completion.'),
  'agentSessions.terminate': signature('[SessionRef]', 'void', 'Ends this owned provider session, preserving journal history.'),
  'agentSessions.resolveInteraction': signature('[SessionRef & {turnId:string,interactionId:string,answer:ProviderInteractionAnswer}]', 'void', "Current Grok or Claude question or permission only. Require the human's explicit answer and the matching provider-specific decision shape. Never infer approval; questions do not authorize commands."),
  'agentSessions.resolveApproval': signature('[SessionRef & {turnId:string,approvalId:string,decision:"allow"|"deny"}]', 'void', 'Use a current pending approval and explicit human decision; never grant permissions by inference.'),
  'reviewTeams.list': signature('[]', 'ReviewTeamPreset[]'),
  'reviewTeams.save': signature('[{team:ReviewTeamPreset}]', 'ReviewTeamPreset', 'Sources are resolved/frozen. Reviewers run independently; architect receives only anonymous reports and cannot waive blocking/missing evidence.'),
  'reviewTeams.remove': signature('[{id:string}]', 'void'),
  'recovery.list': signature('[]', 'RecoveryDocument[]'),
  'recovery.inspect': signature('[RecoveryTarget]', 'RecoveryDocument'),
  'recovery.restore': signature('[{target:RecoveryTarget,expectedFingerprint:string,backupId:string}]', '{fingerprint:string,preservedFingerprint:string}', 'Use inspected fingerprint/backup ID and explicit authorization. session-index is inspection-only. Restore never authorizes uncertain delivery replay.'),
  'workInputs.list': signature('[{ids:string[]}]', 'WorkInputRef[]', 'Use IDs from existing native-picked input grants; this command cannot grant arbitrary filesystem access.'),
  'workFolders.assign': signature('[{taskId:string,grantId?:string}]', 'StoredTask', 'Draft only. Existing owner-picked folder grant or omit for Default; serialized against start.'),
  editorCreate: signature('[EditorOpenRequest & {text?:string}]', 'EditorDocument', 'Creates a new relative file inside the authorized task/project scope.'),
  editorOpen: signature('[EditorOpenRequest]', 'EditorDocument'),
  editorRead: signature('[{id:string,offset?:number,full?:boolean}]', 'EditorDocument', 'Use the open document ID; honor full/window/binary mode and returned range.'),
  editorSave: signature('[{id:string,version:string,start:number,end:number,text:string}]', '{status:"saved",document:EditorDocument}|{status:"conflict",message:string}', 'Use the exact current document version and window range. Conflict is not success; retain unsaved text and re-read.'),
  editorSearch: signature('[{id:string,version:string,query:string,offset:number}]', '{offset?:number,nextOffset:number,done:boolean}'),
  editorClose: signature('[{id:string}]', 'void', 'Does not grant permission to discard unsaved content.'),
  editorLoadDraft: signature('[EditorOpenRequest]', '{document:EditorDocument,text:string,updatedAt:number}|null'),
  editorStoreDraft: signature('[{id:string,document:EditorDocument,text:string}|{id:string,discard:true}]', 'void', 'Store the exact base document with unsaved text; discard is explicit.'),
  editorReveal: signature('[EditorScope & {relativePath?:string}]', 'void'),
  'system.summary': signature('[]', '{version:unknown,repositories:Repository[],tasks:StoredTask[],nativeComputer:boolean}'),
  'system.context': signature('[{taskId:string,chatId?:string}]', '{task:StoredTask,project:{id:string,name:string},workflow:WorkflowSnapshot|WorkFlowSnapshot|null,chats:ChatHistory,session?:AgentSessionSnapshot|null}'),
  'system.windows': signature('[]', '{id:number,title:string,visible:boolean,bounds:{x:number,y:number,width:number,height:number}}[]'),
  'system.screenshot': signature('[{windowId?:number}?]', '{windowId:number,dataUrl:string}', 'Current application window capture only; omit windowId for the main window.'),
  'system.commands': signature('[]', 'CommandCatalog'),
  'computer.run': signature('[{command:string,args?:string[],cwd?:string}]', '{stdout:string,stderr:string}', 'Requires operate scope AND local owner Native computer access. Direct executable + argv, no implicit shell; <=100 args, 30s timeout, 1 MiB output. Omitted cwd is app settings directory. Never treat this permission as authorization for unrelated/destructive actions.'),
}

/** Compact input schemas, so the tool-free architect need not inspect repository code. */
const types = {
  ControlRequest: '{method:string,args?:unknown[],requestId?:string}; args is the positional tuple shown for the method, at most 4 elements; requestId matches [\\w-]{1,160}',
  Provider: '"codex"|"claude"|"antigravity"|"api"',
  AgentExecutionOptions: '{reasoningEffort?:string|null,permissions?:string}; omitted effort inherits, null means explicit provider default, "none" is an explicit supported effort only when catalog says so',
  SessionRef: '{sessionId:string,runId:string}; use exact current values returned by attach/create/resume/reconfigure',
  Preset: 'AgentExecutionOptions & {name:string,agent:string,model:string,permissions:string,apiConnectionId?:string,specialization?:SpecializationSelection}',
  Repository: '{id:string,name:string,path?:string,repoPath?:string,currentBranch?:string,branches?:string[],isWorkspaceMissing?:boolean,isRepoMissing?:boolean,kind?:"git"|"folder"}; preserve returned backend-owned fields/grants',
  Settings: '{theme:string,language:string,uiLanguage:string,defaultIDE:string,autoArchive:string,soundAlerts:boolean,soundType:string,desktopNotifications:boolean,launchAtLogin:boolean,preventSleep:boolean,defaultCodingPreset?:string,defaultReviewPreset?:string,defaultHelperPreset?:string,useMockData?:boolean,preferNativeClaude?:boolean,debugLogging?:boolean,globalWorkspacePath?:string}',
  CreateTaskConfig: 'AgentExecutionOptions & {name:string,repoId:string,description?:string,model?:string,provider?:Provider,providerModel?:string,apiConnectionId?:string,workflow?:string,branchType?:string,branchName?:string,createRequestId?:string,startWorkflow?:boolean,workflowOptions?:{advance:"auto"|"manual",review:boolean,reviewer?:WorkflowReviewSource,planner?:WorkflowReviewSource,fixer?:WorkflowReviewSource},workOptions?:{kind:WorkKind,advance:"auto"|"manual",review:boolean,reviewers:WorkflowReviewSource[],deep?:{workers:WorkflowReviewSource[]},inputIds:string[],folderGrantId?:string}}; Code workflow labels: Auto, Fix a bug, Spec first, Requirements first, Multi-model; Work uses branchType="Folder" and workOptions; Code Branch/Worktree uses saved repository',
  ChatHistory: '{centralTabs:ChatTab[],customTabFeeds:Record<string,FeedItem[]>,activeTabId?:string,recentTabs?:ChatTab[],drafts?:Record<string,string>}; preserve returned FeedItem bodies rather than inventing provider messages',
  ChatTab: '{id:string,name:string,type:"chat"|"file",filePath?:string,baseDir?:string}',
  WorkflowCustomAgentConfiguration: 'AgentExecutionOptions & {provider:Provider,model:string,apiConnectionId?:string}',
  WorkflowReviewSource: 'AgentExecutionOptions & {id:string,presetName:string,configuration?:WorkflowCustomAgentConfiguration,specialization?:SpecializationSelection}; presetName is a saved preset, "@task", or "@custom" with configuration',
  WorkflowHelperSource: 'WorkflowReviewSource & {instructions:string}',
  SpecializationSelection: '{mode:"none"|"standard"|"auto"|"manual",ids?:string[],instructions?:string}; manual <=4 IDs from general/security/reliability/architecture/performance/testing/ux; instructions <=4000 characters; guidance never grants tools/permissions',
  ReviewTeamPreset: '{version:1,id:string,name:string,reviewers:WorkflowReviewSource[],architect:WorkflowReviewSource}; architect must resolve to Claude or API with toolPolicy none; Codex/Antigravity architect is unsupported and must not silently fall back',
  VerificationCommand: '{executable:string,args:string[],timeoutMs:number}; exact explicit argv, no inferred executable checks; proposed model commands require human acceptance',
  CodeProposedStep: '{title:string,instructions:string,acceptance:string[],verification:VerificationCommand[],red?:VerificationCommand,specialization?:SpecializationSelection}',
  WorkflowStep: 'AgentExecutionOptions & {id:string,title:string,instructions:string,acceptance:string[],dependsOn:string[],presetName?:string,configuration?:WorkflowCustomAgentConfiguration,newContext:boolean,stopAfter:boolean,verification:VerificationCommand[],red?:VerificationCommand,specialization?:SpecializationSelection,codePhase?:CodePhase,codeBasis?:number}; codePhase/codeBasis and proposal identities are host-owned: preserve when editing existing snapshots',
  CodePhase: '"discovery"|"investigation"|"requirements"|"specification"|"planning"|"implementation"|"delivery"',
  WorkflowGitPolicy: '{commit:"manual"|"after-plan",merge:"manual"|"after-plan",push:"manual"|"after-plan",targetBranch?:string,remote?:string}; each automatic action requires prior explicit user policy',
  WorkflowPlan: '{title:string,coderPreset:string,coderConfiguration?:WorkflowCustomAgentConfiguration,coderReasoningEffort?:string|null,coderPermissions?:string,coderSpecialization?:SpecializationSelection,reviewerPreset?:string,reviewerConfiguration?:WorkflowCustomAgentConfiguration,reviewerReasoningEffort?:string|null,reviewerSpecialization?:SpecializationSelection,reviewers?:WorkflowReviewSource[],reviewPolicy?:"all",reviewTeam?:ReviewTeamPreset,helpers?:WorkflowHelperSource[],git?:WorkflowGitPolicy,review:boolean,advance:"auto"|"manual",maxFailures:number,maxIterations:number,steps:WorkflowStep[],codeFlow?:CodeFlowDefinition}',
  CodeFlowDefinition: '{version:1,kind:"auto"|"fix-bug"|"spec-first"|"requirements-first"|"multi-model",request:string,interaction?:{version:1},planner?:WorkflowReviewSource,fixer?:WorkflowReviewSource,promptProfile?:CodePromptProfile,multi?:{version:1,explorers?:WorkflowHelperSource[],designers?:WorkflowReviewSource[],reviewCoordinator?:WorkflowReviewSource,reviewDecision?:"auto"|"always"|"never"}}; preserve existing frozen promptProfile; do not fabricate its hash',
  CodePromptProfile: '{version:1,sha256:string,documents:Record<string,string>}; trusted saved instruction snapshot, not an executable authorization',
  WorkKind: '"auto"|"brainstorm"|"deep-brainstorm"|"research"|"write"',
  WorkGateAction: '"answer"|"more"|"evaluate"|"approve"|"approve-with-comments"|"changes"|"cancel"|"finish"|"continue"; actual allowed subset is current pending.actions',
  WorkInputRef: '{id:string,name:string,sha256:string,sizeBytes:number,relativePath?:string}; use backend materialized refs, not invented paths/hashes',
  WorkFlowDefinition: '{version?:1,kind:WorkKind,request:string,advance:"auto"|"manual",executor:WorkflowReviewSource,reviewers:WorkflowReviewSource[],review:boolean,reviewTeam?:ReviewTeamPreset,helpers?:WorkflowHelperSource[],deep?:{workers:WorkflowReviewSource[]},inputs:WorkInputRef[],limits:{maxTurns:number,maxFailures:number,maxFollowUps:number},promptProfile?:CodePromptProfile,roleLabels?:Record<string,string>}',
  RecoveryTarget: '{domain:"settings"|"presets"|"repositories"}|{domain:"tasks",repoId:string}|{domain:"workflow",taskId:string}|{domain:"session-index",taskId:string}|{domain:"session",taskId:string,runId:string}|{domain:"message-queue",taskId:string,sessionId:string}',
  EditorScope: '{repoId:string,taskId?:string,scope:"task"|"project"}',
  EditorOpenRequest: 'EditorScope & {relativePath:string,full?:boolean}',
  EditorDocument: '{id:string,relativePath:string,size:number,version:string,encoding:"utf8"|"utf16le"|"utf16be"|"binary",bom:boolean,mode:"full"|"window"|"binary",text:string,start:number,end:number,canLoadFull:boolean,lineEnding:"LF"|"CRLF"|"CR"|"mixed",warning?:string,backupPath?:string}',
}

export function createCommandCatalog() {
  const system = ['system.summary', 'system.context', 'system.windows', 'system.screenshot', 'system.commands']
  const native = ['computer.run']
  const methods = Object.keys(METHOD_CHANNELS)
  const commands = Object.fromEntries([...methods, ...system, ...native].map(method => {
    const entry = signatures[method]
    if (!entry) throw new Error(`Command metadata missing: ${method}`)
    let scope: 'read' | 'operate' = 'read'
    try { assertCommandScope(method, 'read') } catch { scope = 'operate' }
    return [method, { ...entry, scope }]
  }))
  return {
    version: 1, methods, system, native, commands, types,
    documentation: { locale: 'en', source: 'docs/help/en.json', sourceSha256: helpSourceSha256, purpose: 'Product reference for the application architect and external agents. Documentation and examples never grant permission or replace a current human decision.', guide: structuredClone(englishHelp) },
    envelope: 'ControlRequest: {method,args:[...positional arguments],requestId?}. Empty arguments: []. A one-object request: [{...}]. Required properties lack ?. Current IDs/revisions/hashes must come from authoritative read commands.',
    rules: [
      'This catalog does not expand scope or substitute for user authorization. Owner settings, token rotation, updater mutations, native file pickers and unrestricted IPC are not exposed.',
      'Read current task/workflow/session first. Code uses workflows; Work v1 uses workFlows. Their revisions and run IDs are not interchangeable.',
      'Human acceptance is separate from discussion, model suggestions, auto-advance and starting a workflow. Only answer/approve a current gate when the user authorized that decision.',
      'Reuse the same commandId/clientMessageId/operationId and unchanged payload after unknown acknowledgment; inspect durable receipts before retry. Outer requestId only deduplicates a bounded in-memory transport cache and is not durable proof.',
      'Errors, refusals, blocked/uncertain states and partial receipts are not success. Never bypass stale revision, source fingerprint, editor conflict, cleanup, permission or recovery guards.',
    ],
    examples: {
      'workflows.start': [{ taskId: '<saved task id>', revision: 3, commandId: '<new stable command id>' }],
      'workflows.respond': [{ taskId: '<saved task id>', revision: 3, gateId: '<current codeFlow.pending.id>', commandId: '<new stable command id>', action: 'approve' }],
      'workFlows.respond': [{ taskId: '<saved task id>', runId: '<current snapshot.runId>', revision: 3, gateId: '<current pending.id>', commandId: '<new stable command id>', action: 'answer', answers: [{ questionId: '<current question.id>', text: '<human answer>' }] }],
      'agentSessions.send': [{ sessionId: '<current sessionId>', runId: '<current runId>', clientMessageId: '<stable message id>', text: '<human message>' }],
    },
  }
}
